#----------------------------------------------------------------------------------------------------
# Function to retrieve pids of direct ancestors up to the 10th generation of a given ego(s)
# from SOCSIM microsimulation outputs

# Created on 23-09-2022
# Last modified on 13-08-2024

# This is a modified version of the script "U:/SOCSIM/SOCSIM_Genealogies/SWE_PAA/R_old/Function_Ancestors_Old.R" 
#----------------------------------------------------------------------------------------------------

retrieve_ancestors <- function(egos, opop = opop) {
  
  opop2 <- opop %>% 
    select(pid, mom, pop) %>% 
    # Change 0s (nothing) for the pids of the initial population
    mutate(mom = ifelse(mom == 0, NA, mom), 
           pop = ifelse(pop == 0, NA, pop))
  
  egos <- egos

  ### 3. Grandmothers
  opop2$mm <- opop2$mom[match(opop2$mom, opop2$pid)]
  opop2$mf <- opop2$mom[match(opop2$pop, opop2$pid)]
  ### 3. Grandfathers
  opop2$fm <- opop2$pop[match(opop2$mom, opop2$pid)]  
  opop2$ff <- opop2$pop[match(opop2$pop, opop2$pid)]

  
  ### 4. Great-grandmothers
  opop2$mmm <- opop2$mm[match(opop2$mom, opop2$pid)]
  opop2$mfm <- opop2$mf[match(opop2$mom, opop2$pid)]
  opop2$mmf <- opop2$mm[match(opop2$pop, opop2$pid)]
  opop2$mff <- opop2$mf[match(opop2$pop, opop2$pid)]
  ### 4. Great-grandfathers
  opop2$fmm <- opop2$fm[match(opop2$mom, opop2$pid)]
  opop2$ffm <- opop2$ff[match(opop2$mom, opop2$pid)] 
  opop2$fmf <- opop2$fm[match(opop2$pop, opop2$pid)]
  opop2$fff <- opop2$ff[match(opop2$pop, opop2$pid)]
  
  
  ### 5. Great-great-grandmothers
  opop2$mmmm <- opop2$mmm[match(opop2$mom, opop2$pid)]
  opop2$mmfm <- opop2$mmf[match(opop2$mom, opop2$pid)]
  opop2$mfmm <- opop2$mfm[match(opop2$mom, opop2$pid)]
  opop2$mffm <- opop2$mff[match(opop2$mom, opop2$pid)]
  opop2$mmmf <- opop2$mmm[match(opop2$pop, opop2$pid)]
  opop2$mmff <- opop2$mmf[match(opop2$pop, opop2$pid)]
  opop2$mfmf <- opop2$mfm[match(opop2$pop, opop2$pid)]
  opop2$mfff <- opop2$mff[match(opop2$pop, opop2$pid)]
  ### 5. Great-great-grandfathers
  opop2$fmmm <- opop2$fmm[match(opop2$mom, opop2$pid)]
  opop2$fmfm <- opop2$fmf[match(opop2$mom, opop2$pid)]
  opop2$ffmm <- opop2$ffm[match(opop2$mom, opop2$pid)]
  opop2$fffm <- opop2$fff[match(opop2$mom, opop2$pid)]
  opop2$fmmf <- opop2$fmm[match(opop2$pop, opop2$pid)]
  opop2$fmff <- opop2$fmf[match(opop2$pop, opop2$pid)]
  opop2$ffmf <- opop2$ffm[match(opop2$pop, opop2$pid)]
  opop2$ffff <- opop2$fff[match(opop2$pop, opop2$pid)]

  
  ### 6. Great-great-great-grandmothers
  opop2$mmmmm <- opop2$mmmm[match(opop2$mom, opop2$pid)]
  opop2$mmmfm <- opop2$mmmf[match(opop2$mom, opop2$pid)]
  opop2$mmfmm <- opop2$mmfm[match(opop2$mom, opop2$pid)]
  opop2$mmffm <- opop2$mmff[match(opop2$mom, opop2$pid)]
  opop2$mfmmm <- opop2$mfmm[match(opop2$mom, opop2$pid)]
  opop2$mfmfm <- opop2$mfmf[match(opop2$mom, opop2$pid)]
  opop2$mffmm <- opop2$mffm[match(opop2$mom, opop2$pid)]
  opop2$mfffm <- opop2$mfff[match(opop2$mom, opop2$pid)]
  opop2$mmmmf <- opop2$mmmm[match(opop2$pop, opop2$pid)]
  opop2$mmmff <- opop2$mmmf[match(opop2$pop, opop2$pid)]
  opop2$mmfmf <- opop2$mmfm[match(opop2$pop, opop2$pid)]
  opop2$mmfff <- opop2$mmff[match(opop2$pop, opop2$pid)]
  opop2$mfmmf <- opop2$mfmm[match(opop2$pop, opop2$pid)]
  opop2$mfmff <- opop2$mfmf[match(opop2$pop, opop2$pid)]
  opop2$mffmf <- opop2$mffm[match(opop2$pop, opop2$pid)]
  opop2$mffff <- opop2$mfff[match(opop2$pop, opop2$pid)]
  ### 6. Great-great-great-grandfathers
  opop2$fmmmm <- opop2$fmmm[match(opop2$mom, opop2$pid)]
  opop2$fmmfm <- opop2$fmmf[match(opop2$mom, opop2$pid)]
  opop2$fmfmm <- opop2$fmfm[match(opop2$mom, opop2$pid)]
  opop2$fmffm <- opop2$fmff[match(opop2$mom, opop2$pid)]
  opop2$ffmmm <- opop2$ffmm[match(opop2$mom, opop2$pid)]
  opop2$ffmfm <- opop2$ffmf[match(opop2$mom, opop2$pid)]
  opop2$fffmm <- opop2$fffm[match(opop2$mom, opop2$pid)]
  opop2$ffffm <- opop2$ffff[match(opop2$mom, opop2$pid)]
  opop2$fmmmf <- opop2$fmmm[match(opop2$pop, opop2$pid)]
  opop2$fmmff <- opop2$fmmf[match(opop2$pop, opop2$pid)]
  opop2$fmfmf <- opop2$fmfm[match(opop2$pop, opop2$pid)]
  opop2$fmfff <- opop2$fmff[match(opop2$pop, opop2$pid)]
  opop2$ffmmf <- opop2$ffmm[match(opop2$pop, opop2$pid)]
  opop2$ffmff <- opop2$ffmf[match(opop2$pop, opop2$pid)]
  opop2$fffmf <- opop2$fffm[match(opop2$pop, opop2$pid)]
  opop2$fffff <- opop2$ffff[match(opop2$pop, opop2$pid)]
  
  
  ### 7. Great-great-great-great-grandmothers
  opop2$mmmmmm <- opop2$mmmmm[match(opop2$mom, opop2$pid)]
  opop2$mmmmfm <- opop2$mmmmf[match(opop2$mom, opop2$pid)]
  opop2$mmmfmm <- opop2$mmmfm[match(opop2$mom, opop2$pid)]
  opop2$mmmffm <- opop2$mmmff[match(opop2$mom, opop2$pid)]
  opop2$mmfmmm <- opop2$mmfmm[match(opop2$mom, opop2$pid)]
  opop2$mmfmfm <- opop2$mmfmf[match(opop2$mom, opop2$pid)]
  opop2$mmffmm <- opop2$mmffm[match(opop2$mom, opop2$pid)]
  opop2$mmfffm <- opop2$mmfff[match(opop2$mom, opop2$pid)]
  opop2$mfmmmm <- opop2$mfmmm[match(opop2$mom, opop2$pid)]
  opop2$mfmmfm <- opop2$mfmmf[match(opop2$mom, opop2$pid)]
  opop2$mfmfmm <- opop2$mfmfm[match(opop2$mom, opop2$pid)]
  opop2$mfmffm <- opop2$mfmff[match(opop2$mom, opop2$pid)]
  opop2$mffmmm <- opop2$mffmm[match(opop2$mom, opop2$pid)]
  opop2$mffmfm <- opop2$mffmf[match(opop2$mom, opop2$pid)]
  opop2$mfffmm <- opop2$mfffm[match(opop2$mom, opop2$pid)]
  opop2$mffffm <- opop2$mffff[match(opop2$mom, opop2$pid)]
  opop2$mmmmmf <- opop2$mmmmm[match(opop2$pop, opop2$pid)]
  opop2$mmmmff <- opop2$mmmmf[match(opop2$pop, opop2$pid)]
  opop2$mmmfmf <- opop2$mmmfm[match(opop2$pop, opop2$pid)]
  opop2$mmmfff <- opop2$mmmff[match(opop2$pop, opop2$pid)]
  opop2$mmfmmf <- opop2$mmfmm[match(opop2$pop, opop2$pid)]
  opop2$mmfmff <- opop2$mmfmf[match(opop2$pop, opop2$pid)]
  opop2$mmffmf <- opop2$mmffm[match(opop2$pop, opop2$pid)]
  opop2$mmffff <- opop2$mmfff[match(opop2$pop, opop2$pid)]
  opop2$mfmmmf <- opop2$mfmmm[match(opop2$pop, opop2$pid)]
  opop2$mfmmff <- opop2$mfmmf[match(opop2$pop, opop2$pid)]
  opop2$mfmfmf <- opop2$mfmfm[match(opop2$pop, opop2$pid)]
  opop2$mfmfff <- opop2$mfmff[match(opop2$pop, opop2$pid)]
  opop2$mffmmf <- opop2$mffmm[match(opop2$pop, opop2$pid)]
  opop2$mffmff <- opop2$mffmf[match(opop2$pop, opop2$pid)]
  opop2$mfffmf <- opop2$mfffm[match(opop2$pop, opop2$pid)]
  opop2$mfffff <- opop2$mffff[match(opop2$pop, opop2$pid)]
  ### 7. Great-great-great-great-grandfathers
  opop2$fmmmmm <- opop2$fmmmm[match(opop2$mom, opop2$pid)]
  opop2$fmmmfm <- opop2$fmmmf[match(opop2$mom, opop2$pid)]
  opop2$fmmfmm <- opop2$fmmfm[match(opop2$mom, opop2$pid)]
  opop2$fmmffm <- opop2$fmmff[match(opop2$mom, opop2$pid)]
  opop2$fmfmmm <- opop2$fmfmm[match(opop2$mom, opop2$pid)]
  opop2$fmfmfm <- opop2$fmfmf[match(opop2$mom, opop2$pid)]
  opop2$fmffmm <- opop2$fmffm[match(opop2$mom, opop2$pid)]
  opop2$fmfffm <- opop2$fmfff[match(opop2$mom, opop2$pid)]
  opop2$ffmmmm <- opop2$ffmmm[match(opop2$mom, opop2$pid)]
  opop2$ffmmfm <- opop2$ffmmf[match(opop2$mom, opop2$pid)]
  opop2$ffmfmm <- opop2$ffmfm[match(opop2$mom, opop2$pid)]
  opop2$ffmffm <- opop2$ffmff[match(opop2$mom, opop2$pid)]
  opop2$fffmmm <- opop2$fffmm[match(opop2$mom, opop2$pid)]
  opop2$fffmfm <- opop2$fffmf[match(opop2$mom, opop2$pid)]
  opop2$ffffmm <- opop2$ffffm[match(opop2$mom, opop2$pid)]
  opop2$fffffm <- opop2$fffff[match(opop2$mom, opop2$pid)]
  opop2$fmmmmf <- opop2$fmmmm[match(opop2$pop, opop2$pid)]
  opop2$fmmmff <- opop2$fmmmf[match(opop2$pop, opop2$pid)]
  opop2$fmmfmf <- opop2$fmmfm[match(opop2$pop, opop2$pid)]
  opop2$fmmfff <- opop2$fmmff[match(opop2$pop, opop2$pid)]
  opop2$fmfmmf <- opop2$fmfmm[match(opop2$pop, opop2$pid)]
  opop2$fmfmff <- opop2$fmfmf[match(opop2$pop, opop2$pid)]
  opop2$fmffmf <- opop2$fmffm[match(opop2$pop, opop2$pid)]
  opop2$fmffff <- opop2$fmfff[match(opop2$pop, opop2$pid)]
  opop2$ffmmmf <- opop2$ffmmm[match(opop2$pop, opop2$pid)]
  opop2$ffmmff <- opop2$ffmmf[match(opop2$pop, opop2$pid)]
  opop2$ffmfmf <- opop2$ffmfm[match(opop2$pop, opop2$pid)]
  opop2$ffmfff <- opop2$ffmff[match(opop2$pop, opop2$pid)]
  opop2$fffmmf <- opop2$fffmm[match(opop2$pop, opop2$pid)]
  opop2$fffmff <- opop2$fffmf[match(opop2$pop, opop2$pid)]
  opop2$ffffmf <- opop2$ffffm[match(opop2$pop, opop2$pid)]
  opop2$ffffff <- opop2$fffff[match(opop2$pop, opop2$pid)]
  
  
  ### 8. Great-great-great-great-great-grandmothers
  opop2$mmmmmmm <- opop2$mmmmmm[match(opop2$mom, opop2$pid)]
  opop2$mmmmmfm <- opop2$mmmmmf[match(opop2$mom, opop2$pid)]
  opop2$mmmmfmm <- opop2$mmmmfm[match(opop2$mom, opop2$pid)]
  opop2$mmmmffm <- opop2$mmmmff[match(opop2$mom, opop2$pid)]
  opop2$mmmfmmm <- opop2$mmmfmm[match(opop2$mom, opop2$pid)]
  opop2$mmmfmfm <- opop2$mmmfmf[match(opop2$mom, opop2$pid)]
  opop2$mmmffmm <- opop2$mmmffm[match(opop2$mom, opop2$pid)]
  opop2$mmmfffm <- opop2$mmmfff[match(opop2$mom, opop2$pid)]
  opop2$mmfmmmm <- opop2$mmfmmm[match(opop2$mom, opop2$pid)]
  opop2$mmfmmfm <- opop2$mmfmmf[match(opop2$mom, opop2$pid)]
  opop2$mmfmfmm <- opop2$mmfmfm[match(opop2$mom, opop2$pid)]
  opop2$mmfmffm <- opop2$mmfmff[match(opop2$mom, opop2$pid)]
  opop2$mmffmmm <- opop2$mmffmm[match(opop2$mom, opop2$pid)]
  opop2$mmffmfm <- opop2$mmffmf[match(opop2$mom, opop2$pid)]
  opop2$mmfffmm <- opop2$mmfffm[match(opop2$mom, opop2$pid)]
  opop2$mmffffm <- opop2$mmffff[match(opop2$mom, opop2$pid)]
  opop2$mfmmmmm <- opop2$mfmmmm[match(opop2$mom, opop2$pid)]
  opop2$mfmmmfm <- opop2$mfmmmf[match(opop2$mom, opop2$pid)]
  opop2$mfmmfmm <- opop2$mfmmfm[match(opop2$mom, opop2$pid)]
  opop2$mfmmffm <- opop2$mfmmff[match(opop2$mom, opop2$pid)]
  opop2$mfmfmmm <- opop2$mfmfmm[match(opop2$mom, opop2$pid)]
  opop2$mfmfmfm <- opop2$mfmfmf[match(opop2$mom, opop2$pid)]
  opop2$mfmffmm <- opop2$mfmffm[match(opop2$mom, opop2$pid)]
  opop2$mfmfffm <- opop2$mfmfff[match(opop2$mom, opop2$pid)]
  opop2$mffmmmm <- opop2$mffmmm[match(opop2$mom, opop2$pid)]
  opop2$mffmmfm <- opop2$mffmmf[match(opop2$mom, opop2$pid)]
  opop2$mffmfmm <- opop2$mffmfm[match(opop2$mom, opop2$pid)]
  opop2$mffmffm <- opop2$mffmff[match(opop2$mom, opop2$pid)]
  opop2$mfffmmm <- opop2$mfffmm[match(opop2$mom, opop2$pid)]
  opop2$mfffmfm <- opop2$mfffmf[match(opop2$mom, opop2$pid)]
  opop2$mffffmm <- opop2$mffffm[match(opop2$mom, opop2$pid)]
  opop2$mfffffm <- opop2$mfffff[match(opop2$mom, opop2$pid)]
  opop2$mmmmmmf <- opop2$mmmmmm[match(opop2$pop, opop2$pid)]
  opop2$mmmmmff <- opop2$mmmmmf[match(opop2$pop, opop2$pid)]
  opop2$mmmmfmf <- opop2$mmmmfm[match(opop2$pop, opop2$pid)]
  opop2$mmmmfff <- opop2$mmmmff[match(opop2$pop, opop2$pid)]
  opop2$mmmfmmf <- opop2$mmmfmm[match(opop2$pop, opop2$pid)]
  opop2$mmmfmff <- opop2$mmmfmf[match(opop2$pop, opop2$pid)]
  opop2$mmmffmf <- opop2$mmmffm[match(opop2$pop, opop2$pid)]
  opop2$mmmffff <- opop2$mmmfff[match(opop2$pop, opop2$pid)]
  opop2$mmfmmmf <- opop2$mmfmmm[match(opop2$pop, opop2$pid)]
  opop2$mmfmmff <- opop2$mmfmmf[match(opop2$pop, opop2$pid)]
  opop2$mmfmfmf <- opop2$mmfmfm[match(opop2$pop, opop2$pid)]
  opop2$mmfmfff <- opop2$mmfmff[match(opop2$pop, opop2$pid)]
  opop2$mmffmmf <- opop2$mmffmm[match(opop2$pop, opop2$pid)]
  opop2$mmffmff <- opop2$mmffmf[match(opop2$pop, opop2$pid)]
  opop2$mmfffmf <- opop2$mmfffm[match(opop2$pop, opop2$pid)]
  opop2$mmfffff <- opop2$mmffff[match(opop2$pop, opop2$pid)]
  opop2$mfmmmmf <- opop2$mfmmmm[match(opop2$pop, opop2$pid)]
  opop2$mfmmmff <- opop2$mfmmmf[match(opop2$pop, opop2$pid)]
  opop2$mfmmfmf <- opop2$mfmmfm[match(opop2$pop, opop2$pid)]
  opop2$mfmmfff <- opop2$mfmmff[match(opop2$pop, opop2$pid)]
  opop2$mfmfmmf <- opop2$mfmfmm[match(opop2$pop, opop2$pid)]
  opop2$mfmfmff <- opop2$mfmfmf[match(opop2$pop, opop2$pid)]
  opop2$mfmffmf <- opop2$mfmffm[match(opop2$pop, opop2$pid)]
  opop2$mfmffff <- opop2$mfmfff[match(opop2$pop, opop2$pid)]
  opop2$mffmmmf <- opop2$mffmmm[match(opop2$pop, opop2$pid)]
  opop2$mffmmff <- opop2$mffmmf[match(opop2$pop, opop2$pid)]
  opop2$mffmfmf <- opop2$mffmfm[match(opop2$pop, opop2$pid)]
  opop2$mffmfff <- opop2$mffmff[match(opop2$pop, opop2$pid)]
  opop2$mfffmmf <- opop2$mfffmm[match(opop2$pop, opop2$pid)]
  opop2$mfffmff <- opop2$mfffmf[match(opop2$pop, opop2$pid)]
  opop2$mffffmf <- opop2$mffffm[match(opop2$pop, opop2$pid)]
  opop2$mffffff <- opop2$mfffff[match(opop2$pop, opop2$pid)]
  ### 8. Great-great-great-great-great-grandfathers
  opop2$fmmmmmm <- opop2$fmmmmm[match(opop2$mom, opop2$pid)]
  opop2$fmmmmfm <- opop2$fmmmmf[match(opop2$mom, opop2$pid)]
  opop2$fmmmfmm <- opop2$fmmmfm[match(opop2$mom, opop2$pid)]
  opop2$fmmmffm <- opop2$fmmmff[match(opop2$mom, opop2$pid)]
  opop2$fmmfmmm <- opop2$fmmfmm[match(opop2$mom, opop2$pid)]
  opop2$fmmfmfm <- opop2$fmmfmf[match(opop2$mom, opop2$pid)]
  opop2$fmmffmm <- opop2$fmmffm[match(opop2$mom, opop2$pid)]
  opop2$fmmfffm <- opop2$fmmfff[match(opop2$mom, opop2$pid)]
  opop2$fmfmmmm <- opop2$fmfmmm[match(opop2$mom, opop2$pid)]
  opop2$fmfmmfm <- opop2$fmfmmf[match(opop2$mom, opop2$pid)]
  opop2$fmfmfmm <- opop2$fmfmfm[match(opop2$mom, opop2$pid)]
  opop2$fmfmffm <- opop2$fmfmff[match(opop2$mom, opop2$pid)]
  opop2$fmffmmm <- opop2$fmffmm[match(opop2$mom, opop2$pid)]
  opop2$fmffmfm <- opop2$fmffmf[match(opop2$mom, opop2$pid)]
  opop2$fmfffmm <- opop2$fmfffm[match(opop2$mom, opop2$pid)]
  opop2$fmffffm <- opop2$fmffff[match(opop2$mom, opop2$pid)]
  opop2$ffmmmmm <- opop2$ffmmmm[match(opop2$mom, opop2$pid)]
  opop2$ffmmmfm <- opop2$ffmmmf[match(opop2$mom, opop2$pid)]
  opop2$ffmmfmm <- opop2$ffmmfm[match(opop2$mom, opop2$pid)]
  opop2$ffmmffm <- opop2$ffmmff[match(opop2$mom, opop2$pid)]
  opop2$ffmfmmm <- opop2$ffmfmm[match(opop2$mom, opop2$pid)]
  opop2$ffmfmfm <- opop2$ffmfmf[match(opop2$mom, opop2$pid)]
  opop2$ffmffmm <- opop2$ffmffm[match(opop2$mom, opop2$pid)]
  opop2$ffmfffm <- opop2$ffmfff[match(opop2$mom, opop2$pid)]
  opop2$fffmmmm <- opop2$fffmmm[match(opop2$mom, opop2$pid)]
  opop2$fffmmfm <- opop2$fffmmf[match(opop2$mom, opop2$pid)]
  opop2$fffmfmm <- opop2$fffmfm[match(opop2$mom, opop2$pid)]
  opop2$fffmffm <- opop2$fffmff[match(opop2$mom, opop2$pid)]
  opop2$ffffmmm <- opop2$ffffmm[match(opop2$mom, opop2$pid)]
  opop2$ffffmfm <- opop2$ffffmf[match(opop2$mom, opop2$pid)]
  opop2$fffffmm <- opop2$fffffm[match(opop2$mom, opop2$pid)]
  opop2$ffffffm <- opop2$ffffff[match(opop2$mom, opop2$pid)]
  opop2$fmmmmmf <- opop2$fmmmmm[match(opop2$pop, opop2$pid)]
  opop2$fmmmmff <- opop2$fmmmmf[match(opop2$pop, opop2$pid)]
  opop2$fmmmfmf <- opop2$fmmmfm[match(opop2$pop, opop2$pid)]
  opop2$fmmmfff <- opop2$fmmmff[match(opop2$pop, opop2$pid)]
  opop2$fmmfmmf <- opop2$fmmfmm[match(opop2$pop, opop2$pid)]
  opop2$fmmfmff <- opop2$fmmfmf[match(opop2$pop, opop2$pid)]
  opop2$fmmffmf <- opop2$fmmffm[match(opop2$pop, opop2$pid)]
  opop2$fmmffff <- opop2$fmmfff[match(opop2$pop, opop2$pid)]
  opop2$fmfmmmf <- opop2$fmfmmm[match(opop2$pop, opop2$pid)]
  opop2$fmfmmff <- opop2$fmfmmf[match(opop2$pop, opop2$pid)]
  opop2$fmfmfmf <- opop2$fmfmfm[match(opop2$pop, opop2$pid)]
  opop2$fmfmfff <- opop2$fmfmff[match(opop2$pop, opop2$pid)]
  opop2$fmffmmf <- opop2$fmffmm[match(opop2$pop, opop2$pid)]
  opop2$fmffmff <- opop2$fmffmf[match(opop2$pop, opop2$pid)]
  opop2$fmfffmf <- opop2$fmfffm[match(opop2$pop, opop2$pid)]
  opop2$fmfffff <- opop2$fmffff[match(opop2$pop, opop2$pid)]
  opop2$ffmmmmf <- opop2$ffmmmm[match(opop2$pop, opop2$pid)]
  opop2$ffmmmff <- opop2$ffmmmf[match(opop2$pop, opop2$pid)]
  opop2$ffmmfmf <- opop2$ffmmfm[match(opop2$pop, opop2$pid)]
  opop2$ffmmfff <- opop2$ffmmff[match(opop2$pop, opop2$pid)]
  opop2$ffmfmmf <- opop2$ffmfmm[match(opop2$pop, opop2$pid)]
  opop2$ffmfmff <- opop2$ffmfmf[match(opop2$pop, opop2$pid)]
  opop2$ffmffmf <- opop2$ffmffm[match(opop2$pop, opop2$pid)]
  opop2$ffmffff <- opop2$ffmfff[match(opop2$pop, opop2$pid)]
  opop2$fffmmmf <- opop2$fffmmm[match(opop2$pop, opop2$pid)]
  opop2$fffmmff <- opop2$fffmmf[match(opop2$pop, opop2$pid)]
  opop2$fffmfmf <- opop2$fffmfm[match(opop2$pop, opop2$pid)]
  opop2$fffmfff <- opop2$fffmff[match(opop2$pop, opop2$pid)]
  opop2$ffffmmf <- opop2$ffffmm[match(opop2$pop, opop2$pid)]
  opop2$ffffmff <- opop2$ffffmf[match(opop2$pop, opop2$pid)]
  opop2$fffffmf <- opop2$fffffm[match(opop2$pop, opop2$pid)]
  opop2$fffffff <- opop2$ffffff[match(opop2$pop, opop2$pid)]
  
  
  ### 9. Great-great-great-great-great-great-grandmothers
  opop2$mmmmmmmm <- opop2$mmmmmmm[match(opop2$mom, opop2$pid)]
  opop2$mmmmmmfm <- opop2$mmmmmmf[match(opop2$mom, opop2$pid)]
  opop2$mmmmmfmm <- opop2$mmmmmfm[match(opop2$mom, opop2$pid)]
  opop2$mmmmmffm <- opop2$mmmmmff[match(opop2$mom, opop2$pid)]
  opop2$mmmmfmmm <- opop2$mmmmfmm[match(opop2$mom, opop2$pid)]
  opop2$mmmmfmfm <- opop2$mmmmfmf[match(opop2$mom, opop2$pid)]
  opop2$mmmmffmm <- opop2$mmmmffm[match(opop2$mom, opop2$pid)]
  opop2$mmmmfffm <- opop2$mmmmfff[match(opop2$mom, opop2$pid)]
  opop2$mmmfmmmm <- opop2$mmmfmmm[match(opop2$mom, opop2$pid)]
  opop2$mmmfmmfm <- opop2$mmmfmmf[match(opop2$mom, opop2$pid)]
  opop2$mmmfmfmm <- opop2$mmmfmfm[match(opop2$mom, opop2$pid)]
  opop2$mmmfmffm <- opop2$mmmfmff[match(opop2$mom, opop2$pid)]
  opop2$mmmffmmm <- opop2$mmmffmm[match(opop2$mom, opop2$pid)]
  opop2$mmmffmfm <- opop2$mmmffmf[match(opop2$mom, opop2$pid)]
  opop2$mmmfffmm <- opop2$mmmfffm[match(opop2$mom, opop2$pid)]
  opop2$mmmffffm <- opop2$mmmffff[match(opop2$mom, opop2$pid)]
  opop2$mmfmmmmm <- opop2$mmfmmmm[match(opop2$mom, opop2$pid)]
  opop2$mmfmmmfm <- opop2$mmfmmmf[match(opop2$mom, opop2$pid)]
  opop2$mmfmmfmm <- opop2$mmfmmfm[match(opop2$mom, opop2$pid)]
  opop2$mmfmmffm <- opop2$mmfmmff[match(opop2$mom, opop2$pid)]
  opop2$mmfmfmmm <- opop2$mmfmfmm[match(opop2$mom, opop2$pid)]
  opop2$mmfmfmfm <- opop2$mmfmfmf[match(opop2$mom, opop2$pid)]
  opop2$mmfmffmm <- opop2$mmfmffm[match(opop2$mom, opop2$pid)]
  opop2$mmfmfffm <- opop2$mmfmfff[match(opop2$mom, opop2$pid)]
  opop2$mmffmmmm <- opop2$mmffmmm[match(opop2$mom, opop2$pid)]
  opop2$mmffmmfm <- opop2$mmffmmf[match(opop2$mom, opop2$pid)]
  opop2$mmffmfmm <- opop2$mmffmfm[match(opop2$mom, opop2$pid)]
  opop2$mmffmffm <- opop2$mmffmff[match(opop2$mom, opop2$pid)]
  opop2$mmfffmmm <- opop2$mmfffmm[match(opop2$mom, opop2$pid)]
  opop2$mmfffmfm <- opop2$mmfffmf[match(opop2$mom, opop2$pid)]
  opop2$mmffffmm <- opop2$mmffffm[match(opop2$mom, opop2$pid)]
  opop2$mmfffffm <- opop2$mmfffff[match(opop2$mom, opop2$pid)]
  opop2$mfmmmmmm <- opop2$mfmmmmm[match(opop2$mom, opop2$pid)]
  opop2$mfmmmmfm <- opop2$mfmmmmf[match(opop2$mom, opop2$pid)]
  opop2$mfmmmfmm <- opop2$mfmmmfm[match(opop2$mom, opop2$pid)]
  opop2$mfmmmffm <- opop2$mfmmmff[match(opop2$mom, opop2$pid)]
  opop2$mfmmfmmm <- opop2$mfmmfmm[match(opop2$mom, opop2$pid)]
  opop2$mfmmfmfm <- opop2$mfmmfmf[match(opop2$mom, opop2$pid)]
  opop2$mfmmffmm <- opop2$mfmmffm[match(opop2$mom, opop2$pid)]
  opop2$mfmmfffm <- opop2$mfmmfff[match(opop2$mom, opop2$pid)]
  opop2$mfmfmmmm <- opop2$mfmfmmm[match(opop2$mom, opop2$pid)]
  opop2$mfmfmmfm <- opop2$mfmfmmf[match(opop2$mom, opop2$pid)]
  opop2$mfmfmfmm <- opop2$mfmfmfm[match(opop2$mom, opop2$pid)]
  opop2$mfmfmffm <- opop2$mfmfmff[match(opop2$mom, opop2$pid)]
  opop2$mfmffmmm <- opop2$mfmffmm[match(opop2$mom, opop2$pid)]
  opop2$mfmffmfm <- opop2$mfmffmf[match(opop2$mom, opop2$pid)]
  opop2$mfmfffmm <- opop2$mfmfffm[match(opop2$mom, opop2$pid)]
  opop2$mfmffffm <- opop2$mfmffff[match(opop2$mom, opop2$pid)]
  opop2$mffmmmmm <- opop2$mffmmmm[match(opop2$mom, opop2$pid)]
  opop2$mffmmmfm <- opop2$mffmmmf[match(opop2$mom, opop2$pid)]
  opop2$mffmmfmm <- opop2$mffmmfm[match(opop2$mom, opop2$pid)]
  opop2$mffmmffm <- opop2$mffmmff[match(opop2$mom, opop2$pid)]
  opop2$mffmfmmm <- opop2$mffmfmm[match(opop2$mom, opop2$pid)]
  opop2$mffmfmfm <- opop2$mffmfmf[match(opop2$mom, opop2$pid)]
  opop2$mffmffmm <- opop2$mffmffm[match(opop2$mom, opop2$pid)]
  opop2$mffmfffm <- opop2$mffmfff[match(opop2$mom, opop2$pid)]
  opop2$mfffmmmm <- opop2$mfffmmm[match(opop2$mom, opop2$pid)]
  opop2$mfffmmfm <- opop2$mfffmmf[match(opop2$mom, opop2$pid)]
  opop2$mfffmfmm <- opop2$mfffmfm[match(opop2$mom, opop2$pid)]
  opop2$mfffmffm <- opop2$mfffmff[match(opop2$mom, opop2$pid)]
  opop2$mffffmmm <- opop2$mffffmm[match(opop2$mom, opop2$pid)]
  opop2$mffffmfm <- opop2$mffffmf[match(opop2$mom, opop2$pid)]
  opop2$mfffffmm <- opop2$mfffffm[match(opop2$mom, opop2$pid)]
  opop2$mffffffm <- opop2$mffffff[match(opop2$mom, opop2$pid)]
  opop2$mmmmmmmf <- opop2$mmmmmmm[match(opop2$pop, opop2$pid)]
  opop2$mmmmmmff <- opop2$mmmmmmf[match(opop2$pop, opop2$pid)]
  opop2$mmmmmfmf <- opop2$mmmmmfm[match(opop2$pop, opop2$pid)]
  opop2$mmmmmfff <- opop2$mmmmmff[match(opop2$pop, opop2$pid)]
  opop2$mmmmfmmf <- opop2$mmmmfmm[match(opop2$pop, opop2$pid)]
  opop2$mmmmfmff <- opop2$mmmmfmf[match(opop2$pop, opop2$pid)]
  opop2$mmmmffmf <- opop2$mmmmffm[match(opop2$pop, opop2$pid)]
  opop2$mmmmffff <- opop2$mmmmfff[match(opop2$pop, opop2$pid)]
  opop2$mmmfmmmf <- opop2$mmmfmmm[match(opop2$pop, opop2$pid)]
  opop2$mmmfmmff <- opop2$mmmfmmf[match(opop2$pop, opop2$pid)]
  opop2$mmmfmfmf <- opop2$mmmfmfm[match(opop2$pop, opop2$pid)]
  opop2$mmmfmfff <- opop2$mmmfmff[match(opop2$pop, opop2$pid)]
  opop2$mmmffmmf <- opop2$mmmffmm[match(opop2$pop, opop2$pid)]
  opop2$mmmffmff <- opop2$mmmffmf[match(opop2$pop, opop2$pid)]
  opop2$mmmfffmf <- opop2$mmmfffm[match(opop2$pop, opop2$pid)]
  opop2$mmmfffff <- opop2$mmmffff[match(opop2$pop, opop2$pid)]
  opop2$mmfmmmmf <- opop2$mmfmmmm[match(opop2$pop, opop2$pid)]
  opop2$mmfmmmff <- opop2$mmfmmmf[match(opop2$pop, opop2$pid)]
  opop2$mmfmmfmf <- opop2$mmfmmfm[match(opop2$pop, opop2$pid)]
  opop2$mmfmmfff <- opop2$mmfmmff[match(opop2$pop, opop2$pid)]
  opop2$mmfmfmmf <- opop2$mmfmfmm[match(opop2$pop, opop2$pid)]
  opop2$mmfmfmff <- opop2$mmfmfmf[match(opop2$pop, opop2$pid)]
  opop2$mmfmffmf <- opop2$mmfmffm[match(opop2$pop, opop2$pid)]
  opop2$mmfmffff <- opop2$mmfmfff[match(opop2$pop, opop2$pid)]
  opop2$mmffmmmf <- opop2$mmffmmm[match(opop2$pop, opop2$pid)]
  opop2$mmffmmff <- opop2$mmffmmf[match(opop2$pop, opop2$pid)]
  opop2$mmffmfmf <- opop2$mmffmfm[match(opop2$pop, opop2$pid)]
  opop2$mmffmfff <- opop2$mmffmff[match(opop2$pop, opop2$pid)]
  opop2$mmfffmmf <- opop2$mmfffmm[match(opop2$pop, opop2$pid)]
  opop2$mmfffmff <- opop2$mmfffmf[match(opop2$pop, opop2$pid)]
  opop2$mmffffmf <- opop2$mmffffm[match(opop2$pop, opop2$pid)]
  opop2$mmffffff <- opop2$mmfffff[match(opop2$pop, opop2$pid)]
  opop2$mfmmmmmf <- opop2$mfmmmmm[match(opop2$pop, opop2$pid)]
  opop2$mfmmmmff <- opop2$mfmmmmf[match(opop2$pop, opop2$pid)]
  opop2$mfmmmfmf <- opop2$mfmmmfm[match(opop2$pop, opop2$pid)]
  opop2$mfmmmfff <- opop2$mfmmmff[match(opop2$pop, opop2$pid)]
  opop2$mfmmfmmf <- opop2$mfmmfmm[match(opop2$pop, opop2$pid)]
  opop2$mfmmfmff <- opop2$mfmmfmf[match(opop2$pop, opop2$pid)]
  opop2$mfmmffmf <- opop2$mfmmffm[match(opop2$pop, opop2$pid)]
  opop2$mfmmffff <- opop2$mfmmfff[match(opop2$pop, opop2$pid)]
  opop2$mfmfmmmf <- opop2$mfmfmmm[match(opop2$pop, opop2$pid)]
  opop2$mfmfmmff <- opop2$mfmfmmf[match(opop2$pop, opop2$pid)]
  opop2$mfmfmfmf <- opop2$mfmfmfm[match(opop2$pop, opop2$pid)]
  opop2$mfmfmfff <- opop2$mfmfmff[match(opop2$pop, opop2$pid)]
  opop2$mfmffmmf <- opop2$mfmffmm[match(opop2$pop, opop2$pid)]
  opop2$mfmffmff <- opop2$mfmffmf[match(opop2$pop, opop2$pid)]
  opop2$mfmfffmf <- opop2$mfmfffm[match(opop2$pop, opop2$pid)]
  opop2$mfmfffff <- opop2$mfmffff[match(opop2$pop, opop2$pid)]
  opop2$mffmmmmf <- opop2$mffmmmm[match(opop2$pop, opop2$pid)]
  opop2$mffmmmff <- opop2$mffmmmf[match(opop2$pop, opop2$pid)]
  opop2$mffmmfmf <- opop2$mffmmfm[match(opop2$pop, opop2$pid)]
  opop2$mffmmfff <- opop2$mffmmff[match(opop2$pop, opop2$pid)]
  opop2$mffmfmmf <- opop2$mffmfmm[match(opop2$pop, opop2$pid)]
  opop2$mffmfmff <- opop2$mffmfmf[match(opop2$pop, opop2$pid)]
  opop2$mffmffmf <- opop2$mffmffm[match(opop2$pop, opop2$pid)]
  opop2$mffmffff <- opop2$mffmfff[match(opop2$pop, opop2$pid)]
  opop2$mfffmmmf <- opop2$mfffmmm[match(opop2$pop, opop2$pid)]
  opop2$mfffmmff <- opop2$mfffmmf[match(opop2$pop, opop2$pid)]
  opop2$mfffmfmf <- opop2$mfffmfm[match(opop2$pop, opop2$pid)]
  opop2$mfffmfff <- opop2$mfffmff[match(opop2$pop, opop2$pid)]
  opop2$mffffmmf <- opop2$mffffmm[match(opop2$pop, opop2$pid)]
  opop2$mffffmff <- opop2$mffffmf[match(opop2$pop, opop2$pid)]
  opop2$mfffffmf <- opop2$mfffffm[match(opop2$pop, opop2$pid)]
  opop2$mfffffff <- opop2$mffffff[match(opop2$pop, opop2$pid)]
  ### 9. Great-great-great-great-great-great-grandfathers
  opop2$fmmmmmmm <- opop2$fmmmmmm[match(opop2$mom, opop2$pid)]
  opop2$fmmmmmfm <- opop2$fmmmmmf[match(opop2$mom, opop2$pid)]
  opop2$fmmmmfmm <- opop2$fmmmmfm[match(opop2$mom, opop2$pid)]
  opop2$fmmmmffm <- opop2$fmmmmff[match(opop2$mom, opop2$pid)]
  opop2$fmmmfmmm <- opop2$fmmmfmm[match(opop2$mom, opop2$pid)]
  opop2$fmmmfmfm <- opop2$fmmmfmf[match(opop2$mom, opop2$pid)]
  opop2$fmmmffmm <- opop2$fmmmffm[match(opop2$mom, opop2$pid)]
  opop2$fmmmfffm <- opop2$fmmmfff[match(opop2$mom, opop2$pid)]
  opop2$fmmfmmmm <- opop2$fmmfmmm[match(opop2$mom, opop2$pid)]
  opop2$fmmfmmfm <- opop2$fmmfmmf[match(opop2$mom, opop2$pid)]
  opop2$fmmfmfmm <- opop2$fmmfmfm[match(opop2$mom, opop2$pid)]
  opop2$fmmfmffm <- opop2$fmmfmff[match(opop2$mom, opop2$pid)]
  opop2$fmmffmmm <- opop2$fmmffmm[match(opop2$mom, opop2$pid)]
  opop2$fmmffmfm <- opop2$fmmffmf[match(opop2$mom, opop2$pid)]
  opop2$fmmfffmm <- opop2$fmmfffm[match(opop2$mom, opop2$pid)]
  opop2$fmmffffm <- opop2$fmmffff[match(opop2$mom, opop2$pid)]
  opop2$fmfmmmmm <- opop2$fmfmmmm[match(opop2$mom, opop2$pid)]
  opop2$fmfmmmfm <- opop2$fmfmmmf[match(opop2$mom, opop2$pid)]
  opop2$fmfmmfmm <- opop2$fmfmmfm[match(opop2$mom, opop2$pid)]
  opop2$fmfmmffm <- opop2$fmfmmff[match(opop2$mom, opop2$pid)]
  opop2$fmfmfmmm <- opop2$fmfmfmm[match(opop2$mom, opop2$pid)]
  opop2$fmfmfmfm <- opop2$fmfmfmf[match(opop2$mom, opop2$pid)]
  opop2$fmfmffmm <- opop2$fmfmffm[match(opop2$mom, opop2$pid)]
  opop2$fmfmfffm <- opop2$fmfmfff[match(opop2$mom, opop2$pid)]
  opop2$fmffmmmm <- opop2$fmffmmm[match(opop2$mom, opop2$pid)]
  opop2$fmffmmfm <- opop2$fmffmmf[match(opop2$mom, opop2$pid)]
  opop2$fmffmfmm <- opop2$fmffmfm[match(opop2$mom, opop2$pid)]
  opop2$fmffmffm <- opop2$fmffmff[match(opop2$mom, opop2$pid)]
  opop2$fmfffmmm <- opop2$fmfffmm[match(opop2$mom, opop2$pid)]
  opop2$fmfffmfm <- opop2$fmfffmf[match(opop2$mom, opop2$pid)]
  opop2$fmffffmm <- opop2$fmffffm[match(opop2$mom, opop2$pid)]
  opop2$fmfffffm <- opop2$fmfffff[match(opop2$mom, opop2$pid)]
  opop2$ffmmmmmm <- opop2$ffmmmmm[match(opop2$mom, opop2$pid)]
  opop2$ffmmmmfm <- opop2$ffmmmmf[match(opop2$mom, opop2$pid)]
  opop2$ffmmmfmm <- opop2$ffmmmfm[match(opop2$mom, opop2$pid)]
  opop2$ffmmmffm <- opop2$ffmmmff[match(opop2$mom, opop2$pid)]
  opop2$ffmmfmmm <- opop2$ffmmfmm[match(opop2$mom, opop2$pid)]
  opop2$ffmmfmfm <- opop2$ffmmfmf[match(opop2$mom, opop2$pid)]
  opop2$ffmmffmm <- opop2$ffmmffm[match(opop2$mom, opop2$pid)]
  opop2$ffmmfffm <- opop2$ffmmfff[match(opop2$mom, opop2$pid)]
  opop2$ffmfmmmm <- opop2$ffmfmmm[match(opop2$mom, opop2$pid)]
  opop2$ffmfmmfm <- opop2$ffmfmmf[match(opop2$mom, opop2$pid)]
  opop2$ffmfmfmm <- opop2$ffmfmfm[match(opop2$mom, opop2$pid)]
  opop2$ffmfmffm <- opop2$ffmfmff[match(opop2$mom, opop2$pid)]
  opop2$ffmffmmm <- opop2$ffmffmm[match(opop2$mom, opop2$pid)]
  opop2$ffmffmfm <- opop2$ffmffmf[match(opop2$mom, opop2$pid)]
  opop2$ffmfffmm <- opop2$ffmfffm[match(opop2$mom, opop2$pid)]
  opop2$ffmffffm <- opop2$ffmffff[match(opop2$mom, opop2$pid)]
  opop2$fffmmmmm <- opop2$fffmmmm[match(opop2$mom, opop2$pid)]
  opop2$fffmmmfm <- opop2$fffmmmf[match(opop2$mom, opop2$pid)]
  opop2$fffmmfmm <- opop2$fffmmfm[match(opop2$mom, opop2$pid)]
  opop2$fffmmffm <- opop2$fffmmff[match(opop2$mom, opop2$pid)]
  opop2$fffmfmmm <- opop2$fffmfmm[match(opop2$mom, opop2$pid)]
  opop2$fffmfmfm <- opop2$fffmfmf[match(opop2$mom, opop2$pid)]
  opop2$fffmffmm <- opop2$fffmffm[match(opop2$mom, opop2$pid)]
  opop2$fffmfffm <- opop2$fffmfff[match(opop2$mom, opop2$pid)]
  opop2$ffffmmmm <- opop2$ffffmmm[match(opop2$mom, opop2$pid)]
  opop2$ffffmmfm <- opop2$ffffmmf[match(opop2$mom, opop2$pid)]
  opop2$ffffmfmm <- opop2$ffffmfm[match(opop2$mom, opop2$pid)]
  opop2$ffffmffm <- opop2$ffffmff[match(opop2$mom, opop2$pid)]
  opop2$fffffmmm <- opop2$fffffmm[match(opop2$mom, opop2$pid)]
  opop2$fffffmfm <- opop2$fffffmf[match(opop2$mom, opop2$pid)]
  opop2$ffffffmm <- opop2$ffffffm[match(opop2$mom, opop2$pid)]
  opop2$fffffffm <- opop2$fffffff[match(opop2$mom, opop2$pid)]
  opop2$fmmmmmmf <- opop2$fmmmmmm[match(opop2$pop, opop2$pid)]
  opop2$fmmmmmff <- opop2$fmmmmmf[match(opop2$pop, opop2$pid)]
  opop2$fmmmmfmf <- opop2$fmmmmfm[match(opop2$pop, opop2$pid)]
  opop2$fmmmmfff <- opop2$fmmmmff[match(opop2$pop, opop2$pid)]
  opop2$fmmmfmmf <- opop2$fmmmfmm[match(opop2$pop, opop2$pid)]
  opop2$fmmmfmff <- opop2$fmmmfmf[match(opop2$pop, opop2$pid)]
  opop2$fmmmffmf <- opop2$fmmmffm[match(opop2$pop, opop2$pid)]
  opop2$fmmmffff <- opop2$fmmmfff[match(opop2$pop, opop2$pid)]
  opop2$fmmfmmmf <- opop2$fmmfmmm[match(opop2$pop, opop2$pid)]
  opop2$fmmfmmff <- opop2$fmmfmmf[match(opop2$pop, opop2$pid)]
  opop2$fmmfmfmf <- opop2$fmmfmfm[match(opop2$pop, opop2$pid)]
  opop2$fmmfmfff <- opop2$fmmfmff[match(opop2$pop, opop2$pid)]
  opop2$fmmffmmf <- opop2$fmmffmm[match(opop2$pop, opop2$pid)]
  opop2$fmmffmff <- opop2$fmmffmf[match(opop2$pop, opop2$pid)]
  opop2$fmmfffmf <- opop2$fmmfffm[match(opop2$pop, opop2$pid)]
  opop2$fmmfffff <- opop2$fmmffff[match(opop2$pop, opop2$pid)]
  opop2$fmfmmmmf <- opop2$fmfmmmm[match(opop2$pop, opop2$pid)]
  opop2$fmfmmmff <- opop2$fmfmmmf[match(opop2$pop, opop2$pid)]
  opop2$fmfmmfmf <- opop2$fmfmmfm[match(opop2$pop, opop2$pid)]
  opop2$fmfmmfff <- opop2$fmfmmff[match(opop2$pop, opop2$pid)]
  opop2$fmfmfmmf <- opop2$fmfmfmm[match(opop2$pop, opop2$pid)]
  opop2$fmfmfmff <- opop2$fmfmfmf[match(opop2$pop, opop2$pid)]
  opop2$fmfmffmf <- opop2$fmfmffm[match(opop2$pop, opop2$pid)]
  opop2$fmfmffff <- opop2$fmfmfff[match(opop2$pop, opop2$pid)]
  opop2$fmffmmmf <- opop2$fmffmmm[match(opop2$pop, opop2$pid)]
  opop2$fmffmmff <- opop2$fmffmmf[match(opop2$pop, opop2$pid)]
  opop2$fmffmfmf <- opop2$fmffmfm[match(opop2$pop, opop2$pid)]
  opop2$fmffmfff <- opop2$fmffmff[match(opop2$pop, opop2$pid)]
  opop2$fmfffmmf <- opop2$fmfffmm[match(opop2$pop, opop2$pid)]
  opop2$fmfffmff <- opop2$fmfffmf[match(opop2$pop, opop2$pid)]
  opop2$fmffffmf <- opop2$fmffffm[match(opop2$pop, opop2$pid)]
  opop2$fmffffff <- opop2$fmfffff[match(opop2$pop, opop2$pid)]
  opop2$ffmmmmmf <- opop2$ffmmmmm[match(opop2$pop, opop2$pid)]
  opop2$ffmmmmff <- opop2$ffmmmmf[match(opop2$pop, opop2$pid)]
  opop2$ffmmmfmf <- opop2$ffmmmfm[match(opop2$pop, opop2$pid)]
  opop2$ffmmmfff <- opop2$ffmmmff[match(opop2$pop, opop2$pid)]
  opop2$ffmmfmmf <- opop2$ffmmfmm[match(opop2$pop, opop2$pid)]
  opop2$ffmmfmff <- opop2$ffmmfmf[match(opop2$pop, opop2$pid)]
  opop2$ffmmffmf <- opop2$ffmmffm[match(opop2$pop, opop2$pid)]
  opop2$ffmmffff <- opop2$ffmmfff[match(opop2$pop, opop2$pid)]
  opop2$ffmfmmmf <- opop2$ffmfmmm[match(opop2$pop, opop2$pid)]
  opop2$ffmfmmff <- opop2$ffmfmmf[match(opop2$pop, opop2$pid)]
  opop2$ffmfmfmf <- opop2$ffmfmfm[match(opop2$pop, opop2$pid)]
  opop2$ffmfmfff <- opop2$ffmfmff[match(opop2$pop, opop2$pid)]
  opop2$ffmffmmf <- opop2$ffmffmm[match(opop2$pop, opop2$pid)]
  opop2$ffmffmff <- opop2$ffmffmf[match(opop2$pop, opop2$pid)]
  opop2$ffmfffmf <- opop2$ffmfffm[match(opop2$pop, opop2$pid)]
  opop2$ffmfffff <- opop2$ffmffff[match(opop2$pop, opop2$pid)]
  opop2$fffmmmmf <- opop2$fffmmmm[match(opop2$pop, opop2$pid)]
  opop2$fffmmmff <- opop2$fffmmmf[match(opop2$pop, opop2$pid)]
  opop2$fffmmfmf <- opop2$fffmmfm[match(opop2$pop, opop2$pid)]
  opop2$fffmmfff <- opop2$fffmmff[match(opop2$pop, opop2$pid)]
  opop2$fffmfmmf <- opop2$fffmfmm[match(opop2$pop, opop2$pid)]
  opop2$fffmfmff <- opop2$fffmfmf[match(opop2$pop, opop2$pid)]
  opop2$fffmffmf <- opop2$fffmffm[match(opop2$pop, opop2$pid)]
  opop2$fffmffff <- opop2$fffmfff[match(opop2$pop, opop2$pid)]
  opop2$ffffmmmf <- opop2$ffffmmm[match(opop2$pop, opop2$pid)]
  opop2$ffffmmff <- opop2$ffffmmf[match(opop2$pop, opop2$pid)]
  opop2$ffffmfmf <- opop2$ffffmfm[match(opop2$pop, opop2$pid)]
  opop2$ffffmfff <- opop2$ffffmff[match(opop2$pop, opop2$pid)]
  opop2$fffffmmf <- opop2$fffffmm[match(opop2$pop, opop2$pid)]
  opop2$fffffmff <- opop2$fffffmf[match(opop2$pop, opop2$pid)]
  opop2$ffffffmf <- opop2$ffffffm[match(opop2$pop, opop2$pid)]
  opop2$ffffffff <- opop2$fffffff[match(opop2$pop, opop2$pid)]
  
  
  ### 10. Great-great-great-great-great-great-great-grandmothers
  opop2$mmmmmmmmm <- opop2$mmmmmmmm[match(opop2$mom, opop2$pid)]
  opop2$mmmmmmfmm <- opop2$mmmmmmfm[match(opop2$mom, opop2$pid)]
  opop2$mmmmmfmmm <- opop2$mmmmmfmm[match(opop2$mom, opop2$pid)]
  opop2$mmmmmffmm <- opop2$mmmmmffm[match(opop2$mom, opop2$pid)]
  opop2$mmmmfmmmm <- opop2$mmmmfmmm[match(opop2$mom, opop2$pid)]
  opop2$mmmmfmfmm <- opop2$mmmmfmfm[match(opop2$mom, opop2$pid)]
  opop2$mmmmffmmm <- opop2$mmmmffmm[match(opop2$mom, opop2$pid)]
  opop2$mmmmfffmm <- opop2$mmmmfffm[match(opop2$mom, opop2$pid)]
  opop2$mmmfmmmmm <- opop2$mmmfmmmm[match(opop2$mom, opop2$pid)]
  opop2$mmmfmmfmm <- opop2$mmmfmmfm[match(opop2$mom, opop2$pid)]
  opop2$mmmfmfmmm <- opop2$mmmfmfmm[match(opop2$mom, opop2$pid)]
  opop2$mmmfmffmm <- opop2$mmmfmffm[match(opop2$mom, opop2$pid)]
  opop2$mmmffmmmm <- opop2$mmmffmmm[match(opop2$mom, opop2$pid)]
  opop2$mmmffmfmm <- opop2$mmmffmfm[match(opop2$mom, opop2$pid)]
  opop2$mmmfffmmm <- opop2$mmmfffmm[match(opop2$mom, opop2$pid)]
  opop2$mmmffffmm <- opop2$mmmffffm[match(opop2$mom, opop2$pid)]
  opop2$mmfmmmmmm <- opop2$mmfmmmmm[match(opop2$mom, opop2$pid)]
  opop2$mmfmmmfmm <- opop2$mmfmmmfm[match(opop2$mom, opop2$pid)]
  opop2$mmfmmfmmm <- opop2$mmfmmfmm[match(opop2$mom, opop2$pid)]
  opop2$mmfmmffmm <- opop2$mmfmmffm[match(opop2$mom, opop2$pid)]
  opop2$mmfmfmmmm <- opop2$mmfmfmmm[match(opop2$mom, opop2$pid)]
  opop2$mmfmfmfmm <- opop2$mmfmfmfm[match(opop2$mom, opop2$pid)]
  opop2$mmfmffmmm <- opop2$mmfmffmm[match(opop2$mom, opop2$pid)]
  opop2$mmfmfffmm <- opop2$mmfmfffm[match(opop2$mom, opop2$pid)]
  opop2$mmffmmmmm <- opop2$mmffmmmm[match(opop2$mom, opop2$pid)]
  opop2$mmffmmfmm <- opop2$mmffmmfm[match(opop2$mom, opop2$pid)]
  opop2$mmffmfmmm <- opop2$mmffmfmm[match(opop2$mom, opop2$pid)]
  opop2$mmffmffmm <- opop2$mmffmffm[match(opop2$mom, opop2$pid)]
  opop2$mmfffmmmm <- opop2$mmfffmmm[match(opop2$mom, opop2$pid)]
  opop2$mmfffmfmm <- opop2$mmfffmfm[match(opop2$mom, opop2$pid)]
  opop2$mmffffmmm <- opop2$mmffffmm[match(opop2$mom, opop2$pid)]
  opop2$mmfffffmm <- opop2$mmfffffm[match(opop2$mom, opop2$pid)]
  opop2$mfmmmmmmm <- opop2$mfmmmmmm[match(opop2$mom, opop2$pid)]
  opop2$mfmmmmfmm <- opop2$mfmmmmfm[match(opop2$mom, opop2$pid)]
  opop2$mfmmmfmmm <- opop2$mfmmmfmm[match(opop2$mom, opop2$pid)]
  opop2$mfmmmffmm <- opop2$mfmmmffm[match(opop2$mom, opop2$pid)]
  opop2$mfmmfmmmm <- opop2$mfmmfmmm[match(opop2$mom, opop2$pid)]
  opop2$mfmmfmfmm <- opop2$mfmmfmfm[match(opop2$mom, opop2$pid)]
  opop2$mfmmffmmm <- opop2$mfmmffmm[match(opop2$mom, opop2$pid)]
  opop2$mfmmfffmm <- opop2$mfmmfffm[match(opop2$mom, opop2$pid)]
  opop2$mfmfmmmmm <- opop2$mfmfmmmm[match(opop2$mom, opop2$pid)]
  opop2$mfmfmmfmm <- opop2$mfmfmmfm[match(opop2$mom, opop2$pid)]
  opop2$mfmfmfmmm <- opop2$mfmfmfmm[match(opop2$mom, opop2$pid)]
  opop2$mfmfmffmm <- opop2$mfmfmffm[match(opop2$mom, opop2$pid)]
  opop2$mfmffmmmm <- opop2$mfmffmmm[match(opop2$mom, opop2$pid)]
  opop2$mfmffmfmm <- opop2$mfmffmfm[match(opop2$mom, opop2$pid)]
  opop2$mfmfffmmm <- opop2$mfmfffmm[match(opop2$mom, opop2$pid)]
  opop2$mfmffffmm <- opop2$mfmffffm[match(opop2$mom, opop2$pid)]
  opop2$mffmmmmmm <- opop2$mffmmmmm[match(opop2$mom, opop2$pid)]
  opop2$mffmmmfmm <- opop2$mffmmmfm[match(opop2$mom, opop2$pid)]
  opop2$mffmmfmmm <- opop2$mffmmfmm[match(opop2$mom, opop2$pid)]
  opop2$mffmmffmm <- opop2$mffmmffm[match(opop2$mom, opop2$pid)]
  opop2$mffmfmmmm <- opop2$mffmfmmm[match(opop2$mom, opop2$pid)]
  opop2$mffmfmfmm <- opop2$mffmfmfm[match(opop2$mom, opop2$pid)]
  opop2$mffmffmmm <- opop2$mffmffmm[match(opop2$mom, opop2$pid)]
  opop2$mffmfffmm <- opop2$mffmfffm[match(opop2$mom, opop2$pid)]
  opop2$mfffmmmmm <- opop2$mfffmmmm[match(opop2$mom, opop2$pid)]
  opop2$mfffmmfmm <- opop2$mfffmmfm[match(opop2$mom, opop2$pid)]
  opop2$mfffmfmmm <- opop2$mfffmfmm[match(opop2$mom, opop2$pid)]
  opop2$mfffmffmm <- opop2$mfffmffm[match(opop2$mom, opop2$pid)]
  opop2$mffffmmmm <- opop2$mffffmmm[match(opop2$mom, opop2$pid)]
  opop2$mffffmfmm <- opop2$mffffmfm[match(opop2$mom, opop2$pid)]
  opop2$mfffffmmm <- opop2$mfffffmm[match(opop2$mom, opop2$pid)]
  opop2$mffffffmm <- opop2$mffffffm[match(opop2$mom, opop2$pid)]
  opop2$mmmmmmmfm <- opop2$mmmmmmmf[match(opop2$mom, opop2$pid)]
  opop2$mmmmmmffm <- opop2$mmmmmmff[match(opop2$mom, opop2$pid)]
  opop2$mmmmmfmfm <- opop2$mmmmmfmf[match(opop2$mom, opop2$pid)]
  opop2$mmmmmfffm <- opop2$mmmmmfff[match(opop2$mom, opop2$pid)]
  opop2$mmmmfmmfm <- opop2$mmmmfmmf[match(opop2$mom, opop2$pid)]
  opop2$mmmmfmffm <- opop2$mmmmfmff[match(opop2$mom, opop2$pid)]
  opop2$mmmmffmfm <- opop2$mmmmffmf[match(opop2$mom, opop2$pid)]
  opop2$mmmmffffm <- opop2$mmmmffff[match(opop2$mom, opop2$pid)]
  opop2$mmmfmmmfm <- opop2$mmmfmmmf[match(opop2$mom, opop2$pid)]
  opop2$mmmfmmffm <- opop2$mmmfmmff[match(opop2$mom, opop2$pid)]
  opop2$mmmfmfmfm <- opop2$mmmfmfmf[match(opop2$mom, opop2$pid)]
  opop2$mmmfmfffm <- opop2$mmmfmfff[match(opop2$mom, opop2$pid)]
  opop2$mmmffmmfm <- opop2$mmmffmmf[match(opop2$mom, opop2$pid)]
  opop2$mmmffmffm <- opop2$mmmffmff[match(opop2$mom, opop2$pid)]
  opop2$mmmfffmfm <- opop2$mmmfffmf[match(opop2$mom, opop2$pid)]
  opop2$mmmfffffm <- opop2$mmmfffff[match(opop2$mom, opop2$pid)]
  opop2$mmfmmmmfm <- opop2$mmfmmmmf[match(opop2$mom, opop2$pid)]
  opop2$mmfmmmffm <- opop2$mmfmmmff[match(opop2$mom, opop2$pid)]
  opop2$mmfmmfmfm <- opop2$mmfmmfmf[match(opop2$mom, opop2$pid)]
  opop2$mmfmmfffm <- opop2$mmfmmfff[match(opop2$mom, opop2$pid)]
  opop2$mmfmfmmfm <- opop2$mmfmfmmf[match(opop2$mom, opop2$pid)]
  opop2$mmfmfmffm <- opop2$mmfmfmff[match(opop2$mom, opop2$pid)]
  opop2$mmfmffmfm <- opop2$mmfmffmf[match(opop2$mom, opop2$pid)]
  opop2$mmfmffffm <- opop2$mmfmffff[match(opop2$mom, opop2$pid)]
  opop2$mmffmmmfm <- opop2$mmffmmmf[match(opop2$mom, opop2$pid)]
  opop2$mmffmmffm <- opop2$mmffmmff[match(opop2$mom, opop2$pid)]
  opop2$mmffmfmfm <- opop2$mmffmfmf[match(opop2$mom, opop2$pid)]
  opop2$mmffmfffm <- opop2$mmffmfff[match(opop2$mom, opop2$pid)]
  opop2$mmfffmmfm <- opop2$mmfffmmf[match(opop2$mom, opop2$pid)]
  opop2$mmfffmffm <- opop2$mmfffmff[match(opop2$mom, opop2$pid)]
  opop2$mmffffmfm <- opop2$mmffffmf[match(opop2$mom, opop2$pid)]
  opop2$mmffffffm <- opop2$mmffffff[match(opop2$mom, opop2$pid)]
  opop2$mfmmmmmfm <- opop2$mfmmmmmf[match(opop2$mom, opop2$pid)]
  opop2$mfmmmmffm <- opop2$mfmmmmff[match(opop2$mom, opop2$pid)]
  opop2$mfmmmfmfm <- opop2$mfmmmfmf[match(opop2$mom, opop2$pid)]
  opop2$mfmmmfffm <- opop2$mfmmmfff[match(opop2$mom, opop2$pid)]
  opop2$mfmmfmmfm <- opop2$mfmmfmmf[match(opop2$mom, opop2$pid)]
  opop2$mfmmfmffm <- opop2$mfmmfmff[match(opop2$mom, opop2$pid)]
  opop2$mfmmffmfm <- opop2$mfmmffmf[match(opop2$mom, opop2$pid)]
  opop2$mfmmffffm <- opop2$mfmmffff[match(opop2$mom, opop2$pid)]
  opop2$mfmfmmmfm <- opop2$mfmfmmmf[match(opop2$mom, opop2$pid)]
  opop2$mfmfmmffm <- opop2$mfmfmmff[match(opop2$mom, opop2$pid)]
  opop2$mfmfmfmfm <- opop2$mfmfmfmf[match(opop2$mom, opop2$pid)]
  opop2$mfmfmfffm <- opop2$mfmfmfff[match(opop2$mom, opop2$pid)]
  opop2$mfmffmmfm <- opop2$mfmffmmf[match(opop2$mom, opop2$pid)]
  opop2$mfmffmffm <- opop2$mfmffmff[match(opop2$mom, opop2$pid)]
  opop2$mfmfffmfm <- opop2$mfmfffmf[match(opop2$mom, opop2$pid)]
  opop2$mfmfffffm <- opop2$mfmfffff[match(opop2$mom, opop2$pid)]
  opop2$mffmmmmfm <- opop2$mffmmmmf[match(opop2$mom, opop2$pid)]
  opop2$mffmmmffm <- opop2$mffmmmff[match(opop2$mom, opop2$pid)]
  opop2$mffmmfmfm <- opop2$mffmmfmf[match(opop2$mom, opop2$pid)]
  opop2$mffmmfffm <- opop2$mffmmfff[match(opop2$mom, opop2$pid)]
  opop2$mffmfmmfm <- opop2$mffmfmmf[match(opop2$mom, opop2$pid)]
  opop2$mffmfmffm <- opop2$mffmfmff[match(opop2$mom, opop2$pid)]
  opop2$mffmffmfm <- opop2$mffmffmf[match(opop2$mom, opop2$pid)]
  opop2$mffmffffm <- opop2$mffmffff[match(opop2$mom, opop2$pid)]
  opop2$mfffmmmfm <- opop2$mfffmmmf[match(opop2$mom, opop2$pid)]
  opop2$mfffmmffm <- opop2$mfffmmff[match(opop2$mom, opop2$pid)]
  opop2$mfffmfmfm <- opop2$mfffmfmf[match(opop2$mom, opop2$pid)]
  opop2$mfffmfffm <- opop2$mfffmfff[match(opop2$mom, opop2$pid)]
  opop2$mffffmmfm <- opop2$mffffmmf[match(opop2$mom, opop2$pid)]
  opop2$mffffmffm <- opop2$mffffmff[match(opop2$mom, opop2$pid)]
  opop2$mfffffmfm <- opop2$mfffffmf[match(opop2$mom, opop2$pid)]
  opop2$mfffffffm <- opop2$mfffffff[match(opop2$mom, opop2$pid)]
  opop2$mmmmmmmmf <- opop2$mmmmmmmm[match(opop2$pop, opop2$pid)]
  opop2$mmmmmmfmf <- opop2$mmmmmmfm[match(opop2$pop, opop2$pid)]
  opop2$mmmmmfmmf <- opop2$mmmmmfmm[match(opop2$pop, opop2$pid)]
  opop2$mmmmmffmf <- opop2$mmmmmffm[match(opop2$pop, opop2$pid)]
  opop2$mmmmfmmmf <- opop2$mmmmfmmm[match(opop2$pop, opop2$pid)]
  opop2$mmmmfmfmf <- opop2$mmmmfmfm[match(opop2$pop, opop2$pid)]
  opop2$mmmmffmmf <- opop2$mmmmffmm[match(opop2$pop, opop2$pid)]
  opop2$mmmmfffmf <- opop2$mmmmfffm[match(opop2$pop, opop2$pid)]
  opop2$mmmfmmmmf <- opop2$mmmfmmmm[match(opop2$pop, opop2$pid)]
  opop2$mmmfmmfmf <- opop2$mmmfmmfm[match(opop2$pop, opop2$pid)]
  opop2$mmmfmfmmf <- opop2$mmmfmfmm[match(opop2$pop, opop2$pid)]
  opop2$mmmfmffmf <- opop2$mmmfmffm[match(opop2$pop, opop2$pid)]
  opop2$mmmffmmmf <- opop2$mmmffmmm[match(opop2$pop, opop2$pid)]
  opop2$mmmffmfmf <- opop2$mmmffmfm[match(opop2$pop, opop2$pid)]
  opop2$mmmfffmmf <- opop2$mmmfffmm[match(opop2$pop, opop2$pid)]
  opop2$mmmffffmf <- opop2$mmmffffm[match(opop2$pop, opop2$pid)]
  opop2$mmfmmmmmf <- opop2$mmfmmmmm[match(opop2$pop, opop2$pid)]
  opop2$mmfmmmfmf <- opop2$mmfmmmfm[match(opop2$pop, opop2$pid)]
  opop2$mmfmmfmmf <- opop2$mmfmmfmm[match(opop2$pop, opop2$pid)]
  opop2$mmfmmffmf <- opop2$mmfmmffm[match(opop2$pop, opop2$pid)]
  opop2$mmfmfmmmf <- opop2$mmfmfmmm[match(opop2$pop, opop2$pid)]
  opop2$mmfmfmfmf <- opop2$mmfmfmfm[match(opop2$pop, opop2$pid)]
  opop2$mmfmffmmf <- opop2$mmfmffmm[match(opop2$pop, opop2$pid)]
  opop2$mmfmfffmf <- opop2$mmfmfffm[match(opop2$pop, opop2$pid)]
  opop2$mmffmmmmf <- opop2$mmffmmmm[match(opop2$pop, opop2$pid)]
  opop2$mmffmmfmf <- opop2$mmffmmfm[match(opop2$pop, opop2$pid)]
  opop2$mmffmfmmf <- opop2$mmffmfmm[match(opop2$pop, opop2$pid)]
  opop2$mmffmffmf <- opop2$mmffmffm[match(opop2$pop, opop2$pid)]
  opop2$mmfffmmmf <- opop2$mmfffmmm[match(opop2$pop, opop2$pid)]
  opop2$mmfffmfmf <- opop2$mmfffmfm[match(opop2$pop, opop2$pid)]
  opop2$mmffffmmf <- opop2$mmffffmm[match(opop2$pop, opop2$pid)]
  opop2$mmfffffmf <- opop2$mmfffffm[match(opop2$pop, opop2$pid)]
  opop2$mfmmmmmmf <- opop2$mfmmmmmm[match(opop2$pop, opop2$pid)]
  opop2$mfmmmmfmf <- opop2$mfmmmmfm[match(opop2$pop, opop2$pid)]
  opop2$mfmmmfmmf <- opop2$mfmmmfmm[match(opop2$pop, opop2$pid)]
  opop2$mfmmmffmf <- opop2$mfmmmffm[match(opop2$pop, opop2$pid)]
  opop2$mfmmfmmmf <- opop2$mfmmfmmm[match(opop2$pop, opop2$pid)]
  opop2$mfmmfmfmf <- opop2$mfmmfmfm[match(opop2$pop, opop2$pid)]
  opop2$mfmmffmmf <- opop2$mfmmffmm[match(opop2$pop, opop2$pid)]
  opop2$mfmmfffmf <- opop2$mfmmfffm[match(opop2$pop, opop2$pid)]
  opop2$mfmfmmmmf <- opop2$mfmfmmmm[match(opop2$pop, opop2$pid)]
  opop2$mfmfmmfmf <- opop2$mfmfmmfm[match(opop2$pop, opop2$pid)]
  opop2$mfmfmfmmf <- opop2$mfmfmfmm[match(opop2$pop, opop2$pid)]
  opop2$mfmfmffmf <- opop2$mfmfmffm[match(opop2$pop, opop2$pid)]
  opop2$mfmffmmmf <- opop2$mfmffmmm[match(opop2$pop, opop2$pid)]
  opop2$mfmffmfmf <- opop2$mfmffmfm[match(opop2$pop, opop2$pid)]
  opop2$mfmfffmmf <- opop2$mfmfffmm[match(opop2$pop, opop2$pid)]
  opop2$mfmffffmf <- opop2$mfmffffm[match(opop2$pop, opop2$pid)]
  opop2$mffmmmmmf <- opop2$mffmmmmm[match(opop2$pop, opop2$pid)]
  opop2$mffmmmfmf <- opop2$mffmmmfm[match(opop2$pop, opop2$pid)]
  opop2$mffmmfmmf <- opop2$mffmmfmm[match(opop2$pop, opop2$pid)]
  opop2$mffmmffmf <- opop2$mffmmffm[match(opop2$pop, opop2$pid)]
  opop2$mffmfmmmf <- opop2$mffmfmmm[match(opop2$pop, opop2$pid)]
  opop2$mffmfmfmf <- opop2$mffmfmfm[match(opop2$pop, opop2$pid)]
  opop2$mffmffmmf <- opop2$mffmffmm[match(opop2$pop, opop2$pid)]
  opop2$mffmfffmf <- opop2$mffmfffm[match(opop2$pop, opop2$pid)]
  opop2$mfffmmmmf <- opop2$mfffmmmm[match(opop2$pop, opop2$pid)]
  opop2$mfffmmfmf <- opop2$mfffmmfm[match(opop2$pop, opop2$pid)]
  opop2$mfffmfmmf <- opop2$mfffmfmm[match(opop2$pop, opop2$pid)]
  opop2$mfffmffmf <- opop2$mfffmffm[match(opop2$pop, opop2$pid)]
  opop2$mffffmmmf <- opop2$mffffmmm[match(opop2$pop, opop2$pid)]
  opop2$mffffmfmf <- opop2$mffffmfm[match(opop2$pop, opop2$pid)]
  opop2$mfffffmmf <- opop2$mfffffmm[match(opop2$pop, opop2$pid)]
  opop2$mffffffmf <- opop2$mffffffm[match(opop2$pop, opop2$pid)]
  opop2$mmmmmmmff <- opop2$mmmmmmmf[match(opop2$pop, opop2$pid)]
  opop2$mmmmmmfff <- opop2$mmmmmmff[match(opop2$pop, opop2$pid)]
  opop2$mmmmmfmff <- opop2$mmmmmfmf[match(opop2$pop, opop2$pid)]
  opop2$mmmmmffff <- opop2$mmmmmfff[match(opop2$pop, opop2$pid)]
  opop2$mmmmfmmff <- opop2$mmmmfmmf[match(opop2$pop, opop2$pid)]
  opop2$mmmmfmfff <- opop2$mmmmfmff[match(opop2$pop, opop2$pid)]
  opop2$mmmmffmff <- opop2$mmmmffmf[match(opop2$pop, opop2$pid)]
  opop2$mmmmfffff <- opop2$mmmmffff[match(opop2$pop, opop2$pid)]
  opop2$mmmfmmmff <- opop2$mmmfmmmf[match(opop2$pop, opop2$pid)]
  opop2$mmmfmmfff <- opop2$mmmfmmff[match(opop2$pop, opop2$pid)]
  opop2$mmmfmfmff <- opop2$mmmfmfmf[match(opop2$pop, opop2$pid)]
  opop2$mmmfmffff <- opop2$mmmfmfff[match(opop2$pop, opop2$pid)]
  opop2$mmmffmmff <- opop2$mmmffmmf[match(opop2$pop, opop2$pid)]
  opop2$mmmffmfff <- opop2$mmmffmff[match(opop2$pop, opop2$pid)]
  opop2$mmmfffmff <- opop2$mmmfffmf[match(opop2$pop, opop2$pid)]
  opop2$mmmffffff <- opop2$mmmfffff[match(opop2$pop, opop2$pid)]
  opop2$mmfmmmmff <- opop2$mmfmmmmf[match(opop2$pop, opop2$pid)]
  opop2$mmfmmmfff <- opop2$mmfmmmff[match(opop2$pop, opop2$pid)]
  opop2$mmfmmfmff <- opop2$mmfmmfmf[match(opop2$pop, opop2$pid)]
  opop2$mmfmmffff <- opop2$mmfmmfff[match(opop2$pop, opop2$pid)]
  opop2$mmfmfmmff <- opop2$mmfmfmmf[match(opop2$pop, opop2$pid)]
  opop2$mmfmfmfff <- opop2$mmfmfmff[match(opop2$pop, opop2$pid)]
  opop2$mmfmffmff <- opop2$mmfmffmf[match(opop2$pop, opop2$pid)]
  opop2$mmfmfffff <- opop2$mmfmffff[match(opop2$pop, opop2$pid)]
  opop2$mmffmmmff <- opop2$mmffmmmf[match(opop2$pop, opop2$pid)]
  opop2$mmffmmfff <- opop2$mmffmmff[match(opop2$pop, opop2$pid)]
  opop2$mmffmfmff <- opop2$mmffmfmf[match(opop2$pop, opop2$pid)]
  opop2$mmffmffff <- opop2$mmffmfff[match(opop2$pop, opop2$pid)]
  opop2$mmfffmmff <- opop2$mmfffmmf[match(opop2$pop, opop2$pid)]
  opop2$mmfffmfff <- opop2$mmfffmff[match(opop2$pop, opop2$pid)]
  opop2$mmffffmff <- opop2$mmffffmf[match(opop2$pop, opop2$pid)]
  opop2$mmfffffff <- opop2$mmffffff[match(opop2$pop, opop2$pid)]
  opop2$mfmmmmmff <- opop2$mfmmmmmf[match(opop2$pop, opop2$pid)]
  opop2$mfmmmmfff <- opop2$mfmmmmff[match(opop2$pop, opop2$pid)]
  opop2$mfmmmfmff <- opop2$mfmmmfmf[match(opop2$pop, opop2$pid)]
  opop2$mfmmmffff <- opop2$mfmmmfff[match(opop2$pop, opop2$pid)]
  opop2$mfmmfmmff <- opop2$mfmmfmmf[match(opop2$pop, opop2$pid)]
  opop2$mfmmfmfff <- opop2$mfmmfmff[match(opop2$pop, opop2$pid)]
  opop2$mfmmffmff <- opop2$mfmmffmf[match(opop2$pop, opop2$pid)]
  opop2$mfmmfffff <- opop2$mfmmffff[match(opop2$pop, opop2$pid)]
  opop2$mfmfmmmff <- opop2$mfmfmmmf[match(opop2$pop, opop2$pid)]
  opop2$mfmfmmfff <- opop2$mfmfmmff[match(opop2$pop, opop2$pid)]
  opop2$mfmfmfmff <- opop2$mfmfmfmf[match(opop2$pop, opop2$pid)]
  opop2$mfmfmffff <- opop2$mfmfmfff[match(opop2$pop, opop2$pid)]
  opop2$mfmffmmff <- opop2$mfmffmmf[match(opop2$pop, opop2$pid)]
  opop2$mfmffmfff <- opop2$mfmffmff[match(opop2$pop, opop2$pid)]
  opop2$mfmfffmff <- opop2$mfmfffmf[match(opop2$pop, opop2$pid)]
  opop2$mfmffffff <- opop2$mfmfffff[match(opop2$pop, opop2$pid)]
  opop2$mffmmmmff <- opop2$mffmmmmf[match(opop2$pop, opop2$pid)]
  opop2$mffmmmfff <- opop2$mffmmmff[match(opop2$pop, opop2$pid)]
  opop2$mffmmfmff <- opop2$mffmmfmf[match(opop2$pop, opop2$pid)]
  opop2$mffmmffff <- opop2$mffmmfff[match(opop2$pop, opop2$pid)]
  opop2$mffmfmmff <- opop2$mffmfmmf[match(opop2$pop, opop2$pid)]
  opop2$mffmfmfff <- opop2$mffmfmff[match(opop2$pop, opop2$pid)]
  opop2$mffmffmff <- opop2$mffmffmf[match(opop2$pop, opop2$pid)]
  opop2$mffmfffff <- opop2$mffmffff[match(opop2$pop, opop2$pid)]
  opop2$mfffmmmff <- opop2$mfffmmmf[match(opop2$pop, opop2$pid)]
  opop2$mfffmmfff <- opop2$mfffmmff[match(opop2$pop, opop2$pid)]
  opop2$mfffmfmff <- opop2$mfffmfmf[match(opop2$pop, opop2$pid)]
  opop2$mfffmffff <- opop2$mfffmfff[match(opop2$pop, opop2$pid)]
  opop2$mffffmmff <- opop2$mffffmmf[match(opop2$pop, opop2$pid)]
  opop2$mffffmfff <- opop2$mffffmff[match(opop2$pop, opop2$pid)]
  opop2$mfffffmff <- opop2$mfffffmf[match(opop2$pop, opop2$pid)]
  opop2$mffffffff <- opop2$mfffffff[match(opop2$pop, opop2$pid)]
  ### 10. Great-great-great-great-great-great-great-grandfathers
  opop2$fmmmmmmmm <- opop2$fmmmmmmm[match(opop2$mom, opop2$pid)]
  opop2$fmmmmmfmm <- opop2$fmmmmmfm[match(opop2$mom, opop2$pid)]
  opop2$fmmmmfmmm <- opop2$fmmmmfmm[match(opop2$mom, opop2$pid)]
  opop2$fmmmmffmm <- opop2$fmmmmffm[match(opop2$mom, opop2$pid)]
  opop2$fmmmfmmmm <- opop2$fmmmfmmm[match(opop2$mom, opop2$pid)]
  opop2$fmmmfmfmm <- opop2$fmmmfmfm[match(opop2$mom, opop2$pid)]
  opop2$fmmmffmmm <- opop2$fmmmffmm[match(opop2$mom, opop2$pid)]
  opop2$fmmmfffmm <- opop2$fmmmfffm[match(opop2$mom, opop2$pid)]
  opop2$fmmfmmmmm <- opop2$fmmfmmmm[match(opop2$mom, opop2$pid)]
  opop2$fmmfmmfmm <- opop2$fmmfmmfm[match(opop2$mom, opop2$pid)]
  opop2$fmmfmfmmm <- opop2$fmmfmfmm[match(opop2$mom, opop2$pid)]
  opop2$fmmfmffmm <- opop2$fmmfmffm[match(opop2$mom, opop2$pid)]
  opop2$fmmffmmmm <- opop2$fmmffmmm[match(opop2$mom, opop2$pid)]
  opop2$fmmffmfmm <- opop2$fmmffmfm[match(opop2$mom, opop2$pid)]
  opop2$fmmfffmmm <- opop2$fmmfffmm[match(opop2$mom, opop2$pid)]
  opop2$fmmffffmm <- opop2$fmmffffm[match(opop2$mom, opop2$pid)]
  opop2$fmfmmmmmm <- opop2$fmfmmmmm[match(opop2$mom, opop2$pid)]
  opop2$fmfmmmfmm <- opop2$fmfmmmfm[match(opop2$mom, opop2$pid)]
  opop2$fmfmmfmmm <- opop2$fmfmmfmm[match(opop2$mom, opop2$pid)]
  opop2$fmfmmffmm <- opop2$fmfmmffm[match(opop2$mom, opop2$pid)]
  opop2$fmfmfmmmm <- opop2$fmfmfmmm[match(opop2$mom, opop2$pid)]
  opop2$fmfmfmfmm <- opop2$fmfmfmfm[match(opop2$mom, opop2$pid)]
  opop2$fmfmffmmm <- opop2$fmfmffmm[match(opop2$mom, opop2$pid)]
  opop2$fmfmfffmm <- opop2$fmfmfffm[match(opop2$mom, opop2$pid)]
  opop2$fmffmmmmm <- opop2$fmffmmmm[match(opop2$mom, opop2$pid)]
  opop2$fmffmmfmm <- opop2$fmffmmfm[match(opop2$mom, opop2$pid)]
  opop2$fmffmfmmm <- opop2$fmffmfmm[match(opop2$mom, opop2$pid)]
  opop2$fmffmffmm <- opop2$fmffmffm[match(opop2$mom, opop2$pid)]
  opop2$fmfffmmmm <- opop2$fmfffmmm[match(opop2$mom, opop2$pid)]
  opop2$fmfffmfmm <- opop2$fmfffmfm[match(opop2$mom, opop2$pid)]
  opop2$fmffffmmm <- opop2$fmffffmm[match(opop2$mom, opop2$pid)]
  opop2$fmfffffmm <- opop2$fmfffffm[match(opop2$mom, opop2$pid)]
  opop2$ffmmmmmmm <- opop2$ffmmmmmm[match(opop2$mom, opop2$pid)]
  opop2$ffmmmmfmm <- opop2$ffmmmmfm[match(opop2$mom, opop2$pid)]
  opop2$ffmmmfmmm <- opop2$ffmmmfmm[match(opop2$mom, opop2$pid)]
  opop2$ffmmmffmm <- opop2$ffmmmffm[match(opop2$mom, opop2$pid)]
  opop2$ffmmfmmmm <- opop2$ffmmfmmm[match(opop2$mom, opop2$pid)]
  opop2$ffmmfmfmm <- opop2$ffmmfmfm[match(opop2$mom, opop2$pid)]
  opop2$ffmmffmmm <- opop2$ffmmffmm[match(opop2$mom, opop2$pid)]
  opop2$ffmmfffmm <- opop2$ffmmfffm[match(opop2$mom, opop2$pid)]
  opop2$ffmfmmmmm <- opop2$ffmfmmmm[match(opop2$mom, opop2$pid)]
  opop2$ffmfmmfmm <- opop2$ffmfmmfm[match(opop2$mom, opop2$pid)]
  opop2$ffmfmfmmm <- opop2$ffmfmfmm[match(opop2$mom, opop2$pid)]
  opop2$ffmfmffmm <- opop2$ffmfmffm[match(opop2$mom, opop2$pid)]
  opop2$ffmffmmmm <- opop2$ffmffmmm[match(opop2$mom, opop2$pid)]
  opop2$ffmffmfmm <- opop2$ffmffmfm[match(opop2$mom, opop2$pid)]
  opop2$ffmfffmmm <- opop2$ffmfffmm[match(opop2$mom, opop2$pid)]
  opop2$ffmffffmm <- opop2$ffmffffm[match(opop2$mom, opop2$pid)]
  opop2$fffmmmmmm <- opop2$fffmmmmm[match(opop2$mom, opop2$pid)]
  opop2$fffmmmfmm <- opop2$fffmmmfm[match(opop2$mom, opop2$pid)]
  opop2$fffmmfmmm <- opop2$fffmmfmm[match(opop2$mom, opop2$pid)]
  opop2$fffmmffmm <- opop2$fffmmffm[match(opop2$mom, opop2$pid)]
  opop2$fffmfmmmm <- opop2$fffmfmmm[match(opop2$mom, opop2$pid)]
  opop2$fffmfmfmm <- opop2$fffmfmfm[match(opop2$mom, opop2$pid)]
  opop2$fffmffmmm <- opop2$fffmffmm[match(opop2$mom, opop2$pid)]
  opop2$fffmfffmm <- opop2$fffmfffm[match(opop2$mom, opop2$pid)]
  opop2$ffffmmmmm <- opop2$ffffmmmm[match(opop2$mom, opop2$pid)]
  opop2$ffffmmfmm <- opop2$ffffmmfm[match(opop2$mom, opop2$pid)]
  opop2$ffffmfmmm <- opop2$ffffmfmm[match(opop2$mom, opop2$pid)]
  opop2$ffffmffmm <- opop2$ffffmffm[match(opop2$mom, opop2$pid)]
  opop2$fffffmmmm <- opop2$fffffmmm[match(opop2$mom, opop2$pid)]
  opop2$fffffmfmm <- opop2$fffffmfm[match(opop2$mom, opop2$pid)]
  opop2$ffffffmmm <- opop2$ffffffmm[match(opop2$mom, opop2$pid)]
  opop2$fffffffmm <- opop2$fffffffm[match(opop2$mom, opop2$pid)]
  opop2$fmmmmmmfm <- opop2$fmmmmmmf[match(opop2$mom, opop2$pid)]
  opop2$fmmmmmffm <- opop2$fmmmmmff[match(opop2$mom, opop2$pid)]
  opop2$fmmmmfmfm <- opop2$fmmmmfmf[match(opop2$mom, opop2$pid)]
  opop2$fmmmmfffm <- opop2$fmmmmfff[match(opop2$mom, opop2$pid)]
  opop2$fmmmfmmfm <- opop2$fmmmfmmf[match(opop2$mom, opop2$pid)]
  opop2$fmmmfmffm <- opop2$fmmmfmff[match(opop2$mom, opop2$pid)]
  opop2$fmmmffmfm <- opop2$fmmmffmf[match(opop2$mom, opop2$pid)]
  opop2$fmmmffffm <- opop2$fmmmffff[match(opop2$mom, opop2$pid)]
  opop2$fmmfmmmfm <- opop2$fmmfmmmf[match(opop2$mom, opop2$pid)]
  opop2$fmmfmmffm <- opop2$fmmfmmff[match(opop2$mom, opop2$pid)]
  opop2$fmmfmfmfm <- opop2$fmmfmfmf[match(opop2$mom, opop2$pid)]
  opop2$fmmfmfffm <- opop2$fmmfmfff[match(opop2$mom, opop2$pid)]
  opop2$fmmffmmfm <- opop2$fmmffmmf[match(opop2$mom, opop2$pid)]
  opop2$fmmffmffm <- opop2$fmmffmff[match(opop2$mom, opop2$pid)]
  opop2$fmmfffmfm <- opop2$fmmfffmf[match(opop2$mom, opop2$pid)]
  opop2$fmmfffffm <- opop2$fmmfffff[match(opop2$mom, opop2$pid)]
  opop2$fmfmmmmfm <- opop2$fmfmmmmf[match(opop2$mom, opop2$pid)]
  opop2$fmfmmmffm <- opop2$fmfmmmff[match(opop2$mom, opop2$pid)]
  opop2$fmfmmfmfm <- opop2$fmfmmfmf[match(opop2$mom, opop2$pid)]
  opop2$fmfmmfffm <- opop2$fmfmmfff[match(opop2$mom, opop2$pid)]
  opop2$fmfmfmmfm <- opop2$fmfmfmmf[match(opop2$mom, opop2$pid)]
  opop2$fmfmfmffm <- opop2$fmfmfmff[match(opop2$mom, opop2$pid)]
  opop2$fmfmffmfm <- opop2$fmfmffmf[match(opop2$mom, opop2$pid)]
  opop2$fmfmffffm <- opop2$fmfmffff[match(opop2$mom, opop2$pid)]
  opop2$fmffmmmfm <- opop2$fmffmmmf[match(opop2$mom, opop2$pid)]
  opop2$fmffmmffm <- opop2$fmffmmff[match(opop2$mom, opop2$pid)]
  opop2$fmffmfmfm <- opop2$fmffmfmf[match(opop2$mom, opop2$pid)]
  opop2$fmffmfffm <- opop2$fmffmfff[match(opop2$mom, opop2$pid)]
  opop2$fmfffmmfm <- opop2$fmfffmmf[match(opop2$mom, opop2$pid)]
  opop2$fmfffmffm <- opop2$fmfffmff[match(opop2$mom, opop2$pid)]
  opop2$fmffffmfm <- opop2$fmffffmf[match(opop2$mom, opop2$pid)]
  opop2$fmffffffm <- opop2$fmffffff[match(opop2$mom, opop2$pid)]
  opop2$ffmmmmmfm <- opop2$ffmmmmmf[match(opop2$mom, opop2$pid)]
  opop2$ffmmmmffm <- opop2$ffmmmmff[match(opop2$mom, opop2$pid)]
  opop2$ffmmmfmfm <- opop2$ffmmmfmf[match(opop2$mom, opop2$pid)]
  opop2$ffmmmfffm <- opop2$ffmmmfff[match(opop2$mom, opop2$pid)]
  opop2$ffmmfmmfm <- opop2$ffmmfmmf[match(opop2$mom, opop2$pid)]
  opop2$ffmmfmffm <- opop2$ffmmfmff[match(opop2$mom, opop2$pid)]
  opop2$ffmmffmfm <- opop2$ffmmffmf[match(opop2$mom, opop2$pid)]
  opop2$ffmmffffm <- opop2$ffmmffff[match(opop2$mom, opop2$pid)]
  opop2$ffmfmmmfm <- opop2$ffmfmmmf[match(opop2$mom, opop2$pid)]
  opop2$ffmfmmffm <- opop2$ffmfmmff[match(opop2$mom, opop2$pid)]
  opop2$ffmfmfmfm <- opop2$ffmfmfmf[match(opop2$mom, opop2$pid)]
  opop2$ffmfmfffm <- opop2$ffmfmfff[match(opop2$mom, opop2$pid)]
  opop2$ffmffmmfm <- opop2$ffmffmmf[match(opop2$mom, opop2$pid)]
  opop2$ffmffmffm <- opop2$ffmffmff[match(opop2$mom, opop2$pid)]
  opop2$ffmfffmfm <- opop2$ffmfffmf[match(opop2$mom, opop2$pid)]
  opop2$ffmfffffm <- opop2$ffmfffff[match(opop2$mom, opop2$pid)]
  opop2$fffmmmmfm <- opop2$fffmmmmf[match(opop2$mom, opop2$pid)]
  opop2$fffmmmffm <- opop2$fffmmmff[match(opop2$mom, opop2$pid)]
  opop2$fffmmfmfm <- opop2$fffmmfmf[match(opop2$mom, opop2$pid)]
  opop2$fffmmfffm <- opop2$fffmmfff[match(opop2$mom, opop2$pid)]
  opop2$fffmfmmfm <- opop2$fffmfmmf[match(opop2$mom, opop2$pid)]
  opop2$fffmfmffm <- opop2$fffmfmff[match(opop2$mom, opop2$pid)]
  opop2$fffmffmfm <- opop2$fffmffmf[match(opop2$mom, opop2$pid)]
  opop2$fffmffffm <- opop2$fffmffff[match(opop2$mom, opop2$pid)]
  opop2$ffffmmmfm <- opop2$ffffmmmf[match(opop2$mom, opop2$pid)]
  opop2$ffffmmffm <- opop2$ffffmmff[match(opop2$mom, opop2$pid)]
  opop2$ffffmfmfm <- opop2$ffffmfmf[match(opop2$mom, opop2$pid)]
  opop2$ffffmfffm <- opop2$ffffmfff[match(opop2$mom, opop2$pid)]
  opop2$fffffmmfm <- opop2$fffffmmf[match(opop2$mom, opop2$pid)]
  opop2$fffffmffm <- opop2$fffffmff[match(opop2$mom, opop2$pid)]
  opop2$ffffffmfm <- opop2$ffffffmf[match(opop2$mom, opop2$pid)]
  opop2$ffffffffm <- opop2$ffffffff[match(opop2$mom, opop2$pid)]
  opop2$fmmmmmmmf <- opop2$fmmmmmmm[match(opop2$pop, opop2$pid)]
  opop2$fmmmmmfmf <- opop2$fmmmmmfm[match(opop2$pop, opop2$pid)]
  opop2$fmmmmfmmf <- opop2$fmmmmfmm[match(opop2$pop, opop2$pid)]
  opop2$fmmmmffmf <- opop2$fmmmmffm[match(opop2$pop, opop2$pid)]
  opop2$fmmmfmmmf <- opop2$fmmmfmmm[match(opop2$pop, opop2$pid)]
  opop2$fmmmfmfmf <- opop2$fmmmfmfm[match(opop2$pop, opop2$pid)]
  opop2$fmmmffmmf <- opop2$fmmmffmm[match(opop2$pop, opop2$pid)]
  opop2$fmmmfffmf <- opop2$fmmmfffm[match(opop2$pop, opop2$pid)]
  opop2$fmmfmmmmf <- opop2$fmmfmmmm[match(opop2$pop, opop2$pid)]
  opop2$fmmfmmfmf <- opop2$fmmfmmfm[match(opop2$pop, opop2$pid)]
  opop2$fmmfmfmmf <- opop2$fmmfmfmm[match(opop2$pop, opop2$pid)]
  opop2$fmmfmffmf <- opop2$fmmfmffm[match(opop2$pop, opop2$pid)]
  opop2$fmmffmmmf <- opop2$fmmffmmm[match(opop2$pop, opop2$pid)]
  opop2$fmmffmfmf <- opop2$fmmffmfm[match(opop2$pop, opop2$pid)]
  opop2$fmmfffmmf <- opop2$fmmfffmm[match(opop2$pop, opop2$pid)]
  opop2$fmmffffmf <- opop2$fmmffffm[match(opop2$pop, opop2$pid)]
  opop2$fmfmmmmmf <- opop2$fmfmmmmm[match(opop2$pop, opop2$pid)]
  opop2$fmfmmmfmf <- opop2$fmfmmmfm[match(opop2$pop, opop2$pid)]
  opop2$fmfmmfmmf <- opop2$fmfmmfmm[match(opop2$pop, opop2$pid)]
  opop2$fmfmmffmf <- opop2$fmfmmffm[match(opop2$pop, opop2$pid)]
  opop2$fmfmfmmmf <- opop2$fmfmfmmm[match(opop2$pop, opop2$pid)]
  opop2$fmfmfmfmf <- opop2$fmfmfmfm[match(opop2$pop, opop2$pid)]
  opop2$fmfmffmmf <- opop2$fmfmffmm[match(opop2$pop, opop2$pid)]
  opop2$fmfmfffmf <- opop2$fmfmfffm[match(opop2$pop, opop2$pid)]
  opop2$fmffmmmmf <- opop2$fmffmmmm[match(opop2$pop, opop2$pid)]
  opop2$fmffmmfmf <- opop2$fmffmmfm[match(opop2$pop, opop2$pid)]
  opop2$fmffmfmmf <- opop2$fmffmfmm[match(opop2$pop, opop2$pid)]
  opop2$fmffmffmf <- opop2$fmffmffm[match(opop2$pop, opop2$pid)]
  opop2$fmfffmmmf <- opop2$fmfffmmm[match(opop2$pop, opop2$pid)]
  opop2$fmfffmfmf <- opop2$fmfffmfm[match(opop2$pop, opop2$pid)]
  opop2$fmffffmmf <- opop2$fmffffmm[match(opop2$pop, opop2$pid)]
  opop2$fmfffffmf <- opop2$fmfffffm[match(opop2$pop, opop2$pid)]
  opop2$ffmmmmmmf <- opop2$ffmmmmmm[match(opop2$pop, opop2$pid)]
  opop2$ffmmmmfmf <- opop2$ffmmmmfm[match(opop2$pop, opop2$pid)]
  opop2$ffmmmfmmf <- opop2$ffmmmfmm[match(opop2$pop, opop2$pid)]
  opop2$ffmmmffmf <- opop2$ffmmmffm[match(opop2$pop, opop2$pid)]
  opop2$ffmmfmmmf <- opop2$ffmmfmmm[match(opop2$pop, opop2$pid)]
  opop2$ffmmfmfmf <- opop2$ffmmfmfm[match(opop2$pop, opop2$pid)]
  opop2$ffmmffmmf <- opop2$ffmmffmm[match(opop2$pop, opop2$pid)]
  opop2$ffmmfffmf <- opop2$ffmmfffm[match(opop2$pop, opop2$pid)]
  opop2$ffmfmmmmf <- opop2$ffmfmmmm[match(opop2$pop, opop2$pid)]
  opop2$ffmfmmfmf <- opop2$ffmfmmfm[match(opop2$pop, opop2$pid)]
  opop2$ffmfmfmmf <- opop2$ffmfmfmm[match(opop2$pop, opop2$pid)]
  opop2$ffmfmffmf <- opop2$ffmfmffm[match(opop2$pop, opop2$pid)]
  opop2$ffmffmmmf <- opop2$ffmffmmm[match(opop2$pop, opop2$pid)]
  opop2$ffmffmfmf <- opop2$ffmffmfm[match(opop2$pop, opop2$pid)]
  opop2$ffmfffmmf <- opop2$ffmfffmm[match(opop2$pop, opop2$pid)]
  opop2$ffmffffmf <- opop2$ffmffffm[match(opop2$pop, opop2$pid)]
  opop2$fffmmmmmf <- opop2$fffmmmmm[match(opop2$pop, opop2$pid)]
  opop2$fffmmmfmf <- opop2$fffmmmfm[match(opop2$pop, opop2$pid)]
  opop2$fffmmfmmf <- opop2$fffmmfmm[match(opop2$pop, opop2$pid)]
  opop2$fffmmffmf <- opop2$fffmmffm[match(opop2$pop, opop2$pid)]
  opop2$fffmfmmmf <- opop2$fffmfmmm[match(opop2$pop, opop2$pid)]
  opop2$fffmfmfmf <- opop2$fffmfmfm[match(opop2$pop, opop2$pid)]
  opop2$fffmffmmf <- opop2$fffmffmm[match(opop2$pop, opop2$pid)]
  opop2$fffmfffmf <- opop2$fffmfffm[match(opop2$pop, opop2$pid)]
  opop2$ffffmmmmf <- opop2$ffffmmmm[match(opop2$pop, opop2$pid)]
  opop2$ffffmmfmf <- opop2$ffffmmfm[match(opop2$pop, opop2$pid)]
  opop2$ffffmfmmf <- opop2$ffffmfmm[match(opop2$pop, opop2$pid)]
  opop2$ffffmffmf <- opop2$ffffmffm[match(opop2$pop, opop2$pid)]
  opop2$fffffmmmf <- opop2$fffffmmm[match(opop2$pop, opop2$pid)]
  opop2$fffffmfmf <- opop2$fffffmfm[match(opop2$pop, opop2$pid)]
  opop2$ffffffmmf <- opop2$ffffffmm[match(opop2$pop, opop2$pid)]
  opop2$fffffffmf <- opop2$fffffffm[match(opop2$pop, opop2$pid)]
  opop2$fmmmmmmff <- opop2$fmmmmmmf[match(opop2$pop, opop2$pid)]
  opop2$fmmmmmfff <- opop2$fmmmmmff[match(opop2$pop, opop2$pid)]
  opop2$fmmmmfmff <- opop2$fmmmmfmf[match(opop2$pop, opop2$pid)]
  opop2$fmmmmffff <- opop2$fmmmmfff[match(opop2$pop, opop2$pid)]
  opop2$fmmmfmmff <- opop2$fmmmfmmf[match(opop2$pop, opop2$pid)]
  opop2$fmmmfmfff <- opop2$fmmmfmff[match(opop2$pop, opop2$pid)]
  opop2$fmmmffmff <- opop2$fmmmffmf[match(opop2$pop, opop2$pid)]
  opop2$fmmmfffff <- opop2$fmmmffff[match(opop2$pop, opop2$pid)]
  opop2$fmmfmmmff <- opop2$fmmfmmmf[match(opop2$pop, opop2$pid)]
  opop2$fmmfmmfff <- opop2$fmmfmmff[match(opop2$pop, opop2$pid)]
  opop2$fmmfmfmff <- opop2$fmmfmfmf[match(opop2$pop, opop2$pid)]
  opop2$fmmfmffff <- opop2$fmmfmfff[match(opop2$pop, opop2$pid)]
  opop2$fmmffmmff <- opop2$fmmffmmf[match(opop2$pop, opop2$pid)]
  opop2$fmmffmfff <- opop2$fmmffmff[match(opop2$pop, opop2$pid)]
  opop2$fmmfffmff <- opop2$fmmfffmf[match(opop2$pop, opop2$pid)]
  opop2$fmmffffff <- opop2$fmmfffff[match(opop2$pop, opop2$pid)]
  opop2$fmfmmmmff <- opop2$fmfmmmmf[match(opop2$pop, opop2$pid)]
  opop2$fmfmmmfff <- opop2$fmfmmmff[match(opop2$pop, opop2$pid)]
  opop2$fmfmmfmff <- opop2$fmfmmfmf[match(opop2$pop, opop2$pid)]
  opop2$fmfmmffff <- opop2$fmfmmfff[match(opop2$pop, opop2$pid)]
  opop2$fmfmfmmff <- opop2$fmfmfmmf[match(opop2$pop, opop2$pid)]
  opop2$fmfmfmfff <- opop2$fmfmfmff[match(opop2$pop, opop2$pid)]
  opop2$fmfmffmff <- opop2$fmfmffmf[match(opop2$pop, opop2$pid)]
  opop2$fmfmfffff <- opop2$fmfmffff[match(opop2$pop, opop2$pid)]
  opop2$fmffmmmff <- opop2$fmffmmmf[match(opop2$pop, opop2$pid)]
  opop2$fmffmmfff <- opop2$fmffmmff[match(opop2$pop, opop2$pid)]
  opop2$fmffmfmff <- opop2$fmffmfmf[match(opop2$pop, opop2$pid)]
  opop2$fmffmffff <- opop2$fmffmfff[match(opop2$pop, opop2$pid)]
  opop2$fmfffmmff <- opop2$fmfffmmf[match(opop2$pop, opop2$pid)]
  opop2$fmfffmfff <- opop2$fmfffmff[match(opop2$pop, opop2$pid)]
  opop2$fmffffmff <- opop2$fmffffmf[match(opop2$pop, opop2$pid)]
  opop2$fmfffffff <- opop2$fmffffff[match(opop2$pop, opop2$pid)]
  opop2$ffmmmmmff <- opop2$ffmmmmmf[match(opop2$pop, opop2$pid)]
  opop2$ffmmmmfff <- opop2$ffmmmmff[match(opop2$pop, opop2$pid)]
  opop2$ffmmmfmff <- opop2$ffmmmfmf[match(opop2$pop, opop2$pid)]
  opop2$ffmmmffff <- opop2$ffmmmfff[match(opop2$pop, opop2$pid)]
  opop2$ffmmfmmff <- opop2$ffmmfmmf[match(opop2$pop, opop2$pid)]
  opop2$ffmmfmfff <- opop2$ffmmfmff[match(opop2$pop, opop2$pid)]
  opop2$ffmmffmff <- opop2$ffmmffmf[match(opop2$pop, opop2$pid)]
  opop2$ffmmfffff <- opop2$ffmmffff[match(opop2$pop, opop2$pid)]
  opop2$ffmfmmmff <- opop2$ffmfmmmf[match(opop2$pop, opop2$pid)]
  opop2$ffmfmmfff <- opop2$ffmfmmff[match(opop2$pop, opop2$pid)]
  opop2$ffmfmfmff <- opop2$ffmfmfmf[match(opop2$pop, opop2$pid)]
  opop2$ffmfmffff <- opop2$ffmfmfff[match(opop2$pop, opop2$pid)]
  opop2$ffmffmmff <- opop2$ffmffmmf[match(opop2$pop, opop2$pid)]
  opop2$ffmffmfff <- opop2$ffmffmff[match(opop2$pop, opop2$pid)]
  opop2$ffmfffmff <- opop2$ffmfffmf[match(opop2$pop, opop2$pid)]
  opop2$ffmffffff <- opop2$ffmfffff[match(opop2$pop, opop2$pid)]
  opop2$fffmmmmff <- opop2$fffmmmmf[match(opop2$pop, opop2$pid)]
  opop2$fffmmmfff <- opop2$fffmmmff[match(opop2$pop, opop2$pid)]
  opop2$fffmmfmff <- opop2$fffmmfmf[match(opop2$pop, opop2$pid)]
  opop2$fffmmffff <- opop2$fffmmfff[match(opop2$pop, opop2$pid)]
  opop2$fffmfmmff <- opop2$fffmfmmf[match(opop2$pop, opop2$pid)]
  opop2$fffmfmfff <- opop2$fffmfmff[match(opop2$pop, opop2$pid)]
  opop2$fffmffmff <- opop2$fffmffmf[match(opop2$pop, opop2$pid)]
  opop2$fffmfffff <- opop2$fffmffff[match(opop2$pop, opop2$pid)]
  opop2$ffffmmmff <- opop2$ffffmmmf[match(opop2$pop, opop2$pid)]
  opop2$ffffmmfff <- opop2$ffffmmff[match(opop2$pop, opop2$pid)]
  opop2$ffffmfmff <- opop2$ffffmfmf[match(opop2$pop, opop2$pid)]
  opop2$ffffmffff <- opop2$ffffmfff[match(opop2$pop, opop2$pid)]
  opop2$fffffmmff <- opop2$fffffmmf[match(opop2$pop, opop2$pid)]
  opop2$fffffmfff <- opop2$fffffmff[match(opop2$pop, opop2$pid)]
  opop2$ffffffmff <- opop2$ffffffmf[match(opop2$pop, opop2$pid)]
  opop2$fffffffff <- opop2$ffffffff[match(opop2$pop, opop2$pid)]
  
  opop2 <- opop2 %>% 
    filter(pid %in% egos) %>% 
    rename(ego = pid) %>% 
    mutate(ego_id = ego) %>% 
    pivot_longer(-ego_id, names_to = "kin_type", values_to = "pid") %>% 
    filter(!is.na(pid)) %>% 
    left_join(select(opop, c(pid, fem, dob, dod, mom, lborn, marid, mstat)), by = "pid") 
  
  return(opop2)
}


## Re-code the kin_type for the ancestors

recode_ancestors <- function(opop_ancestors) {
    opop_ancestors <- opop_ancestors %>% 
    mutate(kin_type = case_when(kin_type %in% c("ego") ~ "ego", 
                                kin_type %in% c("mom", "pop") ~ "parents", 
                                kin_type %in% c("mm", "mf", "fm","ff") ~ "gparents", 
                                kin_type %in% c("mmm", "mfm", "mmf", "mff", 
                                                "fmm", "ffm", "fmf", "fff") ~ "ggparents", 
                                kin_type %in% c("mmmm", "mmfm", "mfmm", "mffm", "mmmf", "mmff", "mfmf", "mfff",
                                                "fmmm", "fmfm", "ffmm", "fffm", "fmmf", "fmff", "ffmf", "ffff") ~ "gggparents", 
                                kin_type %in% c("mmmmm", "mmmfm", "mmfmm", "mmffm", "mfmmm", "mfmfm", "mffmm","mfffm", 
                                                "mmmmf", "mmmff", "mmfmf", "mmfff", "mfmmf", "mfmff", "mffmf", "mffff",
                                                "fmmmm", "fmmfm", "fmfmm", "fmffm", "ffmmm", "ffmfm", "fffmm", "ffffm", 
                                                "fmmmf", "fmmff", "fmfmf", "fmfff", "ffmmf", "ffmff", "fffmf", "fffff") ~ "ggggparents", 
                                kin_type %in% c("mmmmmm", "mmmmfm", "mmmfmm", "mmmffm", "mmfmmm", "mmfmfm", "mmffmm", "mmfffm",
                                                "mfmmmm", "mfmmfm", "mfmfmm", "mfmffm", "mffmmm", "mffmfm", "mfffmm", "mffffm",
                                                "mmmmmf", "mmmmff", "mmmfmf", "mmmfff", "mmfmmf", "mmfmff", "mmffmf", "mmffff",
                                                "mfmmmf", "mfmmff", "mfmfmf", "mfmfff", "mffmmf", "mffmff", "mfffmf", "mfffff",
                                                "fmmmmm", "fmmmfm", "fmmfmm", "fmmffm", "fmfmmm", "fmfmfm", "fmffmm", "fmfffm",
                                                "ffmmmm", "ffmmfm", "ffmfmm", "ffmffm", "fffmmm", "fffmfm", "ffffmm", "fffffm",
                                                "fmmmmf", "fmmmff", "fmmfmf", "fmmfff", "fmfmmf", "fmfmff", "fmffmf", "fmffff",
                                                "ffmmmf", "ffmmff", "ffmfmf", "ffmfff", "fffmmf", "fffmff", "ffffmf", "ffffff") ~ "gggggparents", 
                                kin_type %in% c("mmmmmmm", "mmmmmfm", "mmmmfmm", "mmmmffm", "mmmfmmm", "mmmfmfm", "mmmffmm", "mmmfffm",
                                                "mmfmmmm", "mmfmmfm", "mmfmfmm", "mmfmffm", "mmffmmm", "mmffmfm", "mmfffmm", "mmffffm",
                                                "mfmmmmm", "mfmmmfm", "mfmmfmm", "mfmmffm", "mfmfmmm", "mfmfmfm", "mfmffmm", "mfmfffm",
                                                "mffmmmm", "mffmmfm", "mffmfmm", "mffmffm", "mfffmmm", "mfffmfm", "mffffmm", "mfffffm",
                                                "mmmmmmf", "mmmmmff", "mmmmfmf", "mmmmfff", "mmmfmmf", "mmmfmff", "mmmffmf", "mmmffff",
                                                "mmfmmmf", "mmfmmff", "mmfmfmf", "mmfmfff", "mmffmmf", "mmffmff", "mmfffmf", "mmfffff",
                                                "mfmmmmf", "mfmmmff", "mfmmfmf", "mfmmfff", "mfmfmmf", "mfmfmff", "mfmffmf", "mfmffff",
                                                "mffmmmf", "mffmmff", "mffmfmf", "mffmfff", "mfffmmf", "mfffmff", "mffffmf", "mffffff",
                                                "fmmmmmm", "fmmmmfm", "fmmmfmm", "fmmmffm", "fmmfmmm", "fmmfmfm", "fmmffmm", "fmmfffm",
                                                "fmfmmmm", "fmfmmfm", "fmfmfmm", "fmfmffm", "fmffmmm", "fmffmfm", "fmfffmm", "fmffffm",
                                                "ffmmmmm", "ffmmmfm", "ffmmfmm", "ffmmffm", "ffmfmmm", "ffmfmfm", "ffmffmm", "ffmfffm",
                                                "fffmmmm", "fffmmfm", "fffmfmm", "fffmffm", "ffffmmm", "ffffmfm", "fffffmm", "ffffffm",
                                                "fmmmmmf", "fmmmmff", "fmmmfmf", "fmmmfff", "fmmfmmf", "fmmfmff", "fmmffmf", "fmmffff",
                                                "fmfmmmf", "fmfmmff", "fmfmfmf", "fmfmfff", "fmffmmf", "fmffmff", "fmfffmf", "fmfffff",
                                                "ffmmmmf", "ffmmmff", "ffmmfmf", "ffmmfff", "ffmfmmf", "ffmfmff", "ffmffmf", "ffmffff",
                                                "fffmmmf", "fffmmff", "fffmfmf", "fffmfff", "ffffmmf", "ffffmff", "fffffmf", "fffffff") ~ "ggggggparents", 
                                kin_type %in% c("mmmmmmmm", "mmmmmmfm", "mmmmmfmm", "mmmmmffm", "mmmmfmmm", "mmmmfmfm", "mmmmffmm", "mmmmfffm", 
                                                "mmmfmmmm", "mmmfmmfm", "mmmfmfmm", "mmmfmffm", "mmmffmmm", "mmmffmfm", "mmmfffmm", "mmmffffm", 
                                                "mmfmmmmm", "mmfmmmfm", "mmfmmfmm", "mmfmmffm", "mmfmfmmm", "mmfmfmfm", "mmfmffmm", "mmfmfffm",
                                                "mmffmmmm", "mmffmmfm", "mmffmfmm", "mmffmffm", "mmfffmmm", "mmfffmfm", "mmffffmm", "mmfffffm", 
                                                "mfmmmmmm", "mfmmmmfm", "mfmmmfmm", "mfmmmffm", "mfmmfmmm", "mfmmfmfm", "mfmmffmm", "mfmmfffm", 
                                                "mfmfmmmm", "mfmfmmfm", "mfmfmfmm", "mfmfmffm", "mfmffmmm", "mfmffmfm", "mfmfffmm", "mfmffffm",
                                                "mffmmmmm", "mffmmmfm", "mffmmfmm", "mffmmffm", "mffmfmmm", "mffmfmfm", "mffmffmm", "mffmfffm", 
                                                "mfffmmmm", "mfffmmfm", "mfffmfmm", "mfffmffm", "mffffmmm", "mffffmfm", "mfffffmm", "mffffffm", 
                                                "mmmmmmmf", "mmmmmmff", "mmmmmfmf", "mmmmmfff", "mmmmfmmf", "mmmmfmff", "mmmmffmf", "mmmmffff",
                                                "mmmfmmmf", "mmmfmmff", "mmmfmfmf", "mmmfmfff", "mmmffmmf", "mmmffmff", "mmmfffmf", "mmmfffff", 
                                                "mmfmmmmf", "mmfmmmff", "mmfmmfmf", "mmfmmfff", "mmfmfmmf", "mmfmfmff", "mmfmffmf", "mmfmffff", 
                                                "mmffmmmf", "mmffmmff", "mmffmfmf", "mmffmfff", "mmfffmmf", "mmfffmff", "mmffffmf", "mmffffff",
                                                "mfmmmmmf", "mfmmmmff", "mfmmmfmf", "mfmmmfff", "mfmmfmmf", "mfmmfmff", "mfmmffmf", "mfmmffff", 
                                                "mfmfmmmf", "mfmfmmff", "mfmfmfmf", "mfmfmfff", "mfmffmmf", "mfmffmff", "mfmfffmf", "mfmfffff", 
                                                "mffmmmmf", "mffmmmff", "mffmmfmf", "mffmmfff", "mffmfmmf", "mffmfmff", "mffmffmf", "mffmffff",
                                                "mfffmmmf", "mfffmmff", "mfffmfmf", "mfffmfff", "mffffmmf", "mffffmff", "mfffffmf", "mfffffff", 
                                                "fmmmmmmm", "fmmmmmfm", "fmmmmfmm", "fmmmmffm", "fmmmfmmm", "fmmmfmfm", "fmmmffmm", "fmmmfffm", 
                                                "fmmfmmmm", "fmmfmmfm", "fmmfmfmm", "fmmfmffm", "fmmffmmm", "fmmffmfm", "fmmfffmm", "fmmffffm",
                                                "fmfmmmmm", "fmfmmmfm", "fmfmmfmm", "fmfmmffm", "fmfmfmmm", "fmfmfmfm", "fmfmffmm", "fmfmfffm", 
                                                "fmffmmmm", "fmffmmfm", "fmffmfmm", "fmffmffm", "fmfffmmm", "fmfffmfm", "fmffffmm", "fmfffffm", 
                                                "ffmmmmmm", "ffmmmmfm", "ffmmmfmm", "ffmmmffm", "ffmmfmmm", "ffmmfmfm", "ffmmffmm", "ffmmfffm",
                                                "ffmfmmmm", "ffmfmmfm", "ffmfmfmm", "ffmfmffm", "ffmffmmm", "ffmffmfm", "ffmfffmm", "ffmffffm", 
                                                "fffmmmmm", "fffmmmfm", "fffmmfmm", "fffmmffm", "fffmfmmm", "fffmfmfm", "fffmffmm", "fffmfffm", 
                                                "ffffmmmm", "ffffmmfm", "ffffmfmm", "ffffmffm", "fffffmmm", "fffffmfm", "ffffffmm", "fffffffm",
                                                "fmmmmmmf", "fmmmmmff", "fmmmmfmf", "fmmmmfff", "fmmmfmmf", "fmmmfmff", "fmmmffmf", "fmmmffff", 
                                                "fmmfmmmf", "fmmfmmff", "fmmfmfmf", "fmmfmfff", "fmmffmmf", "fmmffmff", "fmmfffmf", "fmmfffff", 
                                                "fmfmmmmf", "fmfmmmff", "fmfmmfmf", "fmfmmfff", "fmfmfmmf", "fmfmfmff", "fmfmffmf", "fmfmffff", 
                                                "fmffmmmf", "fmffmmff", "fmffmfmf", "fmffmfff", "fmfffmmf", "fmfffmff", "fmffffmf", "fmffffff", 
                                                "ffmmmmmf", "ffmmmmff", "ffmmmfmf", "ffmmmfff", "ffmmfmmf", "ffmmfmff", "ffmmffmf", "ffmmffff", 
                                                "ffmfmmmf", "ffmfmmff", "ffmfmfmf", "ffmfmfff", "ffmffmmf", "ffmffmff", "ffmfffmf", "ffmfffff", 
                                                "fffmmmmf", "fffmmmff", "fffmmfmf", "fffmmfff", "fffmfmmf", "fffmfmff", "fffmffmf", "fffmffff", 
                                                "ffffmmmf", "ffffmmff", "ffffmfmf", "ffffmfff", "fffffmmf", "fffffmff", "ffffffmf", "ffffffff") ~ "gggggggparents", 
                                kin_type %in% c("mmmmmmmmm", "mmmmmmfmm", "mmmmmfmmm", "mmmmmffmm", "mmmmfmmmm", "mmmmfmfmm", "mmmmffmmm", "mmmmfffmm", 
                                                "mmmfmmmmm", "mmmfmmfmm", "mmmfmfmmm", "mmmfmffmm", "mmmffmmmm", "mmmffmfmm", "mmmfffmmm", "mmmffffmm", 
                                                "mmfmmmmmm", "mmfmmmfmm", "mmfmmfmmm", "mmfmmffmm", "mmfmfmmmm", "mmfmfmfmm", "mmfmffmmm", "mmfmfffmm", 
                                                "mmffmmmmm", "mmffmmfmm", "mmffmfmmm", "mmffmffmm", "mmfffmmmm", "mmfffmfmm", "mmffffmmm", "mmfffffmm", 
                                                "mfmmmmmmm", "mfmmmmfmm", "mfmmmfmmm", "mfmmmffmm", "mfmmfmmmm", "mfmmfmfmm", "mfmmffmmm", "mfmmfffmm", 
                                                "mfmfmmmmm", "mfmfmmfmm", "mfmfmfmmm", "mfmfmffmm", "mfmffmmmm", "mfmffmfmm", "mfmfffmmm", "mfmffffmm", 
                                                "mffmmmmmm", "mffmmmfmm", "mffmmfmmm", "mffmmffmm", "mffmfmmmm", "mffmfmfmm", "mffmffmmm", "mffmfffmm", 
                                                "mfffmmmmm", "mfffmmfmm", "mfffmfmmm", "mfffmffmm", "mffffmmmm", "mffffmfmm", "mfffffmmm", "mffffffmm", 
                                                "mmmmmmmfm", "mmmmmmffm", "mmmmmfmfm", "mmmmmfffm", "mmmmfmmfm", "mmmmfmffm", "mmmmffmfm", "mmmmffffm", 
                                                "mmmfmmmfm", "mmmfmmffm", "mmmfmfmfm", "mmmfmfffm", "mmmffmmfm", "mmmffmffm", "mmmfffmfm", "mmmfffffm", 
                                                "mmfmmmmfm", "mmfmmmffm", "mmfmmfmfm", "mmfmmfffm", "mmfmfmmfm", "mmfmfmffm", "mmfmffmfm", "mmfmffffm", 
                                                "mmffmmmfm", "mmffmmffm", "mmffmfmfm", "mmffmfffm", "mmfffmmfm", "mmfffmffm", "mmffffmfm", "mmffffffm", 
                                                "mfmmmmmfm", "mfmmmmffm", "mfmmmfmfm", "mfmmmfffm", "mfmmfmmfm", "mfmmfmffm", "mfmmffmfm", "mfmmffffm", 
                                                "mfmfmmmfm", "mfmfmmffm", "mfmfmfmfm", "mfmfmfffm", "mfmffmmfm", "mfmffmffm", "mfmfffmfm", "mfmfffffm", 
                                                "mffmmmmfm", "mffmmmffm", "mffmmfmfm", "mffmmfffm", "mffmfmmfm", "mffmfmffm", "mffmffmfm", "mffmffffm", 
                                                "mfffmmmfm", "mfffmmffm", "mfffmfmfm", "mfffmfffm", "mffffmmfm", "mffffmffm", "mfffffmfm", "mfffffffm", 
                                                "mmmmmmmmf", "mmmmmmfmf", "mmmmmfmmf", "mmmmmffmf", "mmmmfmmmf", "mmmmfmfmf", "mmmmffmmf", "mmmmfffmf", 
                                                "mmmfmmmmf", "mmmfmmfmf", "mmmfmfmmf", "mmmfmffmf", "mmmffmmmf", "mmmffmfmf", "mmmfffmmf", "mmmffffmf", 
                                                "mmfmmmmmf", "mmfmmmfmf", "mmfmmfmmf", "mmfmmffmf", "mmfmfmmmf", "mmfmfmfmf", "mmfmffmmf", "mmfmfffmf", 
                                                "mmffmmmmf", "mmffmmfmf", "mmffmfmmf", "mmffmffmf", "mmfffmmmf", "mmfffmfmf", "mmffffmmf", "mmfffffmf", 
                                                "mfmmmmmmf", "mfmmmmfmf", "mfmmmfmmf", "mfmmmffmf", "mfmmfmmmf", "mfmmfmfmf", "mfmmffmmf", "mfmmfffmf", 
                                                "mfmfmmmmf", "mfmfmmfmf", "mfmfmfmmf", "mfmfmffmf", "mfmffmmmf", "mfmffmfmf", "mfmfffmmf", "mfmffffmf", 
                                                "mffmmmmmf", "mffmmmfmf", "mffmmfmmf", "mffmmffmf", "mffmfmmmf", "mffmfmfmf", "mffmffmmf", "mffmfffmf", 
                                                "mfffmmmmf", "mfffmmfmf", "mfffmfmmf", "mfffmffmf", "mffffmmmf", "mffffmfmf", "mfffffmmf", "mffffffmf", 
                                                "mmmmmmmff", "mmmmmmfff", "mmmmmfmff", "mmmmmffff", "mmmmfmmff", "mmmmfmfff", "mmmmffmff", "mmmmfffff", 
                                                "mmmfmmmff", "mmmfmmfff", "mmmfmfmff", "mmmfmffff", "mmmffmmff", "mmmffmfff", "mmmfffmff", "mmmffffff", 
                                                "mmfmmmmff", "mmfmmmfff", "mmfmmfmff", "mmfmmffff", "mmfmfmmff", "mmfmfmfff", "mmfmffmff", "mmfmfffff", 
                                                "mmffmmmff", "mmffmmfff", "mmffmfmff", "mmffmffff", "mmfffmmff", "mmfffmfff", "mmffffmff", "mmfffffff", 
                                                "mfmmmmmff", "mfmmmmfff", "mfmmmfmff", "mfmmmffff", "mfmmfmmff", "mfmmfmfff", "mfmmffmff", "mfmmfffff", 
                                                "mfmfmmmff", "mfmfmmfff", "mfmfmfmff", "mfmfmffff", "mfmffmmff", "mfmffmfff", "mfmfffmff", "mfmffffff", 
                                                "mffmmmmff", "mffmmmfff", "mffmmfmff", "mffmmffff", "mffmfmmff", "mffmfmfff", "mffmffmff", "mffmfffff", 
                                                "mfffmmmff", "mfffmmfff", "mfffmfmff", "mfffmffff", "mffffmmff", "mffffmfff", "mfffffmff", "mffffffff", 
                                                "fmmmmmmmm", "fmmmmmfmm", "fmmmmfmmm", "fmmmmffmm", "fmmmfmmmm", "fmmmfmfmm", "fmmmffmmm", "fmmmfffmm", 
                                                "fmmfmmmmm", "fmmfmmfmm", "fmmfmfmmm", "fmmfmffmm", "fmmffmmmm", "fmmffmfmm", "fmmfffmmm", "fmmffffmm", 
                                                "fmfmmmmmm", "fmfmmmfmm", "fmfmmfmmm", "fmfmmffmm", "fmfmfmmmm", "fmfmfmfmm", "fmfmffmmm", "fmfmfffmm", 
                                                "fmffmmmmm", "fmffmmfmm", "fmffmfmmm", "fmffmffmm", "fmfffmmmm", "fmfffmfmm", "fmffffmmm", "fmfffffmm", 
                                                "ffmmmmmmm", "ffmmmmfmm", "ffmmmfmmm", "ffmmmffmm", "ffmmfmmmm", "ffmmfmfmm", "ffmmffmmm", "ffmmfffmm", 
                                                "ffmfmmmmm", "ffmfmmfmm", "ffmfmfmmm", "ffmfmffmm", "ffmffmmmm", "ffmffmfmm", "ffmfffmmm", "ffmffffmm", 
                                                "fffmmmmmm", "fffmmmfmm", "fffmmfmmm", "fffmmffmm", "fffmfmmmm", "fffmfmfmm", "fffmffmmm", "fffmfffmm", 
                                                "ffffmmmmm", "ffffmmfmm", "ffffmfmmm", "ffffmffmm", "fffffmmmm", "fffffmfmm", "ffffffmmm", "fffffffmm", 
                                                "fmmmmmmfm", "fmmmmmffm", "fmmmmfmfm", "fmmmmfffm", "fmmmfmmfm", "fmmmfmffm", "fmmmffmfm", "fmmmffffm", 
                                                "fmmfmmmfm", "fmmfmmffm", "fmmfmfmfm", "fmmfmfffm", "fmmffmmfm", "fmmffmffm", "fmmfffmfm", "fmmfffffm", 
                                                "fmfmmmmfm", "fmfmmmffm", "fmfmmfmfm", "fmfmmfffm", "fmfmfmmfm", "fmfmfmffm", "fmfmffmfm", "fmfmffffm", 
                                                "fmffmmmfm", "fmffmmffm", "fmffmfmfm", "fmffmfffm", "fmfffmmfm", "fmfffmffm", "fmffffmfm", "fmffffffm", 
                                                "ffmmmmmfm", "ffmmmmffm", "ffmmmfmfm", "ffmmmfffm", "ffmmfmmfm", "ffmmfmffm", "ffmmffmfm", "ffmmffffm", 
                                                "ffmfmmmfm", "ffmfmmffm", "ffmfmfmfm", "ffmfmfffm", "ffmffmmfm", "ffmffmffm", "ffmfffmfm", "ffmfffffm", 
                                                "fffmmmmfm", "fffmmmffm", "fffmmfmfm", "fffmmfffm", "fffmfmmfm", "fffmfmffm", "fffmffmfm", "fffmffffm", 
                                                "ffffmmmfm", "ffffmmffm", "ffffmfmfm", "ffffmfffm", "fffffmmfm", "fffffmffm", "ffffffmfm", "ffffffffm", 
                                                "fmmmmmmmf", "fmmmmmfmf", "fmmmmfmmf", "fmmmmffmf", "fmmmfmmmf", "fmmmfmfmf", "fmmmffmmf", "fmmmfffmf", 
                                                "fmmfmmmmf", "fmmfmmfmf", "fmmfmfmmf", "fmmfmffmf", "fmmffmmmf", "fmmffmfmf", "fmmfffmmf", "fmmffffmf", 
                                                "fmfmmmmmf", "fmfmmmfmf", "fmfmmfmmf", "fmfmmffmf", "fmfmfmmmf", "fmfmfmfmf", "fmfmffmmf", "fmfmfffmf", 
                                                "fmffmmmmf", "fmffmmfmf", "fmffmfmmf", "fmffmffmf", "fmfffmmmf", "fmfffmfmf", "fmffffmmf", "fmfffffmf", 
                                                "ffmmmmmmf", "ffmmmmfmf", "ffmmmfmmf", "ffmmmffmf", "ffmmfmmmf", "ffmmfmfmf", "ffmmffmmf", "ffmmfffmf", 
                                                "ffmfmmmmf", "ffmfmmfmf", "ffmfmfmmf", "ffmfmffmf", "ffmffmmmf", "ffmffmfmf", "ffmfffmmf", "ffmffffmf", 
                                                "fffmmmmmf", "fffmmmfmf", "fffmmfmmf", "fffmmffmf", "fffmfmmmf", "fffmfmfmf", "fffmffmmf", "fffmfffmf", 
                                                "ffffmmmmf", "ffffmmfmf", "ffffmfmmf", "ffffmffmf", "fffffmmmf", "fffffmfmf", "ffffffmmf", "fffffffmf", 
                                                "fmmmmmmff", "fmmmmmfff", "fmmmmfmff", "fmmmmffff", "fmmmfmmff", "fmmmfmfff", "fmmmffmff", "fmmmfffff", 
                                                "fmmfmmmff", "fmmfmmfff", "fmmfmfmff", "fmmfmffff", "fmmffmmff", "fmmffmfff", "fmmfffmff", "fmmffffff", 
                                                "fmfmmmmff", "fmfmmmfff", "fmfmmfmff", "fmfmmffff", "fmfmfmmff", "fmfmfmfff", "fmfmffmff", "fmfmfffff", 
                                                "fmffmmmff", "fmffmmfff", "fmffmfmff", "fmffmffff", "fmfffmmff", "fmfffmfff", "fmffffmff", "fmfffffff", 
                                                "ffmmmmmff", "ffmmmmfff", "ffmmmfmff", "ffmmmffff", "ffmmfmmff", "ffmmfmfff", "ffmmffmff", "ffmmfffff", 
                                                "ffmfmmmff", "ffmfmmfff", "ffmfmfmff", "ffmfmffff", "ffmffmmff", "ffmffmfff", "ffmfffmff", "ffmffffff", 
                                                "fffmmmmff", "fffmmmfff", "fffmmfmff", "fffmmffff", "fffmfmmff", "fffmfmfff", "fffmffmff", "fffmfffff", 
                                                "ffffmmmff", "ffffmmfff", "ffffmfmff", "ffffmffff", "fffffmmff", "fffffmfff", "ffffffmff", "fffffffff") ~ "ggggggggparents",
                                TRUE ~ NA_character_))
    return(opop_ancestors)
}